"""sales assessment, sector groups, business source profile

Revision ID: 4da1505e557d
Revises: fc5aa89ae7f1
Create Date: 2026-09-18 22:03:09.823136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4da1505e557d'
down_revision: Union[str, None] = 'fc5aa89ae7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('analysis_job_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('level_reason', sa.Text(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('primary_service_id', sa.Integer(), nullable=True),
    sa.Column('secondary_service_id', sa.Integer(), nullable=True),
    sa.Column('top_opportunity', sa.Text(), nullable=True),
    sa.Column('why_call', sa.Text(), nullable=True),
    sa.Column('talking_point', sa.Text(), nullable=True),
    sa.Column('sales_note', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['primary_service_id'], ['services_catalog.id'], ),
    sa.ForeignKeyConstraint(['secondary_service_id'], ['services_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('businesses', sa.Column('category_label', sa.String(length=120), nullable=True))
    op.add_column('businesses', sa.Column('maps_url', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('source_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('source_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sectors', sa.Column('group_name', sa.String(length=80), nullable=True))
    op.add_column('sectors', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sectors', 'is_active')
    op.drop_column('sectors', 'group_name')
    op.drop_column('businesses', 'source_profile')
    op.drop_column('businesses', 'source_checked_at')
    op.drop_column('businesses', 'last_review_at')
    op.drop_column('businesses', 'maps_url')
    op.drop_column('businesses', 'category_label')
    op.drop_table('sales_assessments')
    # ### end Alembic commands ###
