"""sprint1 job status terminology and scoring insufficient data

Revision ID: 62678d303a02
Revises: 839707bbc8f7
Create Date: 2026-09-18 02:20:22.151996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '62678d303a02'
down_revision: Union[str, None] = '839707bbc8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'discovery_jobs',
        sa.Column('item_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    op.add_column(
        'opportunity_scores',
        sa.Column('status', sa.String(length=20), nullable=False, server_default='scored'),
    )
    op.alter_column('opportunity_scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunity_scores', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('opportunity_scores', 'status')
    op.drop_column('discovery_jobs', 'item_errors')
    # ### end Alembic commands ###
