"""initial schema

Revision ID: 839707bbc8f7
Revises: 
Create Date: 2026-09-18 02:02:52.867677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '839707bbc8f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('terms_url', sa.String(length=500), nullable=True),
    sa.Column('quota_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cache_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_oauth', sa.Boolean(), nullable=False),
    sa.Column('attribution_requirements', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_region_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('search_radius_m', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('google_place_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('keyword_variants', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_sectors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('required_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunity_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sales_arguments', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('deliverables', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('default_priority', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=False),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_review_count', sa.Integer(), nullable=True),
    sa.Column('photo_count', sa.Integer(), nullable=True),
    sa.Column('discovery_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('crm_stage', sa.String(length=40), nullable=False),
    sa.Column('opportunity_score_total', sa.Integer(), nullable=True),
    sa.Column('sales_priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_analysis_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id')
    )
    op.create_table('discovery_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('found_new', sa.Integer(), nullable=False),
    sa.Column('found_existing', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stages_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_usage_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cost_units', sa.Float(), nullable=False),
    sa.Column('quota_period', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('competitor_business_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['competitor_business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('from_stage', sa.String(length=40), nullable=True),
    sa.Column('to_stage', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_job_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['discovery_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'business_id', name='uq_discovery_job_result')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('problems_summary', sa.Text(), nullable=True),
    sa.Column('opportunities_summary', sa.Text(), nullable=True),
    sa.Column('recommended_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('marketing_goals', sa.Text(), nullable=True),
    sa.Column('work_plan', sa.Text(), nullable=True),
    sa.Column('price_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('analysis_job_id', sa.Integer(), nullable=True),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('analysis_job_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('finding', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('based_on_metric_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('mchttasarim_opportunity', sa.Text(), nullable=True),
    sa.Column('recommended_service_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('analysis_job_id', sa.Integer(), nullable=True),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('based_on_finding_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('analysis_job_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('matched_rule', sa.Text(), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('ai_justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_recommendations')
    op.drop_table('opportunity_scores')
    op.drop_table('findings')
    op.drop_table('business_metrics')
    op.drop_table('proposals')
    op.drop_table('discovery_job_results')
    op.drop_table('crm_activities')
    op.drop_table('competitor_snapshots')
    op.drop_table('api_usage_ledger')
    op.drop_table('analysis_jobs')
    op.drop_table('discovery_jobs')
    op.drop_table('businesses')
    op.drop_table('users')
    op.drop_table('services_catalog')
    op.drop_table('sectors')
    op.drop_table('regions')
    op.drop_table('integrations_registry')
    # ### end Alembic commands ###
