"""add analysis_job_id to competitor_snapshots

Revision ID: 869b3a0e1c10
Revises: 62678d303a02
Create Date: 2026-09-18 02:44:09.318879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '869b3a0e1c10'
down_revision: Union[str, None] = '62678d303a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_snapshots', sa.Column('analysis_job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'competitor_snapshots', 'analysis_jobs', ['analysis_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitor_snapshots', type_='foreignkey')
    op.drop_column('competitor_snapshots', 'analysis_job_id')
    # ### end Alembic commands ###
