"""add opening_hours to businesses

Revision ID: b1b31360e6b0
Revises: 869b3a0e1c10
Create Date: 2026-09-18 03:15:30.626605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b1b31360e6b0'
down_revision: Union[str, None] = '869b3a0e1c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('opening_hours', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'opening_hours')
    # ### end Alembic commands ###
