"""crm fields on businesses

Revision ID: f5973b82f890
Revises: 84baa1102f43
Create Date: 2026-09-19 00:31:13.152944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f5973b82f890'
down_revision: Union[str, None] = '84baa1102f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('crm_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('businesses', sa.Column('staff_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'staff_note')
    op.drop_column('businesses', 'crm_updated_at')
    # ### end Alembic commands ###
