"""add email to businesses

Revision ID: fc5aa89ae7f1
Revises: b1b31360e6b0
Create Date: 2026-09-18 13:42:18.133545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc5aa89ae7f1'
down_revision: Union[str, None] = 'b1b31360e6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'email')
    # ### end Alembic commands ###
