"""Personel için "Sorun nasıl çözülür?" rehberleri (Çözüm Rehberi kütüphanesi).

Her rehber, teknik bilgisi olmayan bir personelin tespit edilen sorunu anlayıp Mchttasarım hizmetiyle çözebilmesi için 8 bölümden oluşur:
A) Sorun nedir? · B) Neden önemli? · C) Mchttasarım nasıl çözer? · D) Adım adım ne yapacağız? · E) Müşteriye nasıl anlatılır? ·
F) Hangi hizmeti teklif edeceğiz? · G) Müşteriye soracağımız sorular · H) İşlem sonrası kontrol.

Kurallar: etkiler KESİN sonuç gibi yazılmaz ("olabilir", "etkileyebilir"); metinler işletmeye özel bir olguyu uydurmaz. `{isletme}`, `{sehir}`, `{sektor}`,
`{kelime}` yer tutucuları, rehber bir işletme için açıldığında o işletmenin gerçek verileriyle, genel kütüphanede ise genel ifadelerle doldurulur.
`check_keys`: analiz kontrol anahtarları ("web.<anahtar>", "gbp.<anahtar>", "social.<anahtar>"); rehberin hangi tespitlerle eşleştiğini belirler.
"""

from dataclasses import dataclass

WEB, GBP, SOSYAL, REKLAM, MATBAA = "Web Sitesi", "Google İşletme Profili", "Sosyal Medya", "Reklam", "Matbaa ve Promosyon"
CATEGORIES = [WEB, GBP, SOSYAL, REKLAM, MATBAA]


@dataclass(frozen=True)
class Guide:
    id: str
    category: str
    title: str
    services: tuple[str, ...]
    check_keys: tuple[str, ...]
    what: str
    why: str
    solution: str
    steps: tuple[str, ...]
    pitch: str
    offer: str
    questions: tuple[str, ...]
    verify: tuple[str, ...]


def _g(id, category, title, services, check_keys, what, why, solution, steps, pitch, offer, questions, verify) -> Guide:
    return Guide(id, category, title, tuple(services), tuple(check_keys), what, why, solution, tuple(steps), pitch, offer, tuple(questions), tuple(verify))


_GUIDES: list[Guide] = [
    # =============================================================== WEB SİTESİ
    _g("web_yok", WEB, "Web sitesi yok", ["Kurumsal Web Sitesi", "Yerel SEO"], ["web.presence"],
       "İşletmeye ait doğrulanmış bir web sitesi bulunamadı. Google'da işletmeyi arayan kişi, işletmenin hizmetlerini ve iletişim bilgilerini anlatan kendi sayfasını göremiyor olabilir.",
       "Web sitesi olmayan işletme, Google'da arama yapan potansiyel müşterilere kendini tam olarak gösteremez ve güven vermekte zorlanabilir. Reklam ve yerel arama çalışmaları için de bir 'ev' eksik kalır.",
       "Mchttasarım işletmeye mobil uyumlu, hızlı bir kurumsal web sitesi kurar; hizmet sayfalarını, iletişim noktalarını ve yerel arama (SEO) altyapısını birlikte hazırlar.",
       ["Görüşmede gerçekten web sitesi olmadığını işletme sahibinden teyit et (analiz kaynaklardan bulamadı; işletmenin bilmediği bir sitesi olabilir).", "İşletme sahibinden logo ve mevcut görselleri iste.", "Hizmetlerin, çalışma saatlerinin ve iletişim bilgilerinin listesini topla.", "Site kapsamını belirle: ana sayfa, hizmetler, hakkımızda, iletişim (isteğe bağlı: randevu/rezervasyon).", "Alan adı ve barındırma durumunu öğren (yoksa Mchttasarım önerir).", "Teklifi hazırla ve onay al.", "Tasarım ve içerik sürecini başlat; yayından önce kontrol listesiyle test et (mobil, hız, form, telefon bağlantısı).", "SEO ve Google İşletme Profili bağlantısını kontrol et."],
       "{isletme} için internette hizmetlerinizi ve iletişim bilgilerinizi tek yerde gösteren bir web sitesi göremedik. {sehir} bölgesinde {kelime} arayan kişilerin size ulaşmadan önce bakabileceği bir sayfa oluşturmanızı öneriyoruz.",
       "Kurumsal web sitesi + yerel SEO",
       ["Şu anda web siteniz var mı?", "Müşterileriniz sizi internette nasıl buluyor?", "Sitenizden size müşteri geliyor mu?", "Google'da hangi kelimelerde görünmek istiyorsunuz?", "Fiyat/hizmet bilgisini müşterilere şimdi nasıl iletiyorsunuz?"],
       ["Site yayında ve telefondan açılıyor mu?", "Ana sayfada telefon, adres ve harita bağlantısı var mı?", "Google İşletme Profilindeki web sitesi alanı yeni siteye bağlandı mı?", "Google'da işletme adı aratıldığında site birkaç gün/hafta içinde görünmeye başladı mı?"]),

    _g("web_acilmiyor", WEB, "Web sitesi açılmıyor / erişilemiyor", ["Web Tasarım", "Kurumsal Web Sitesi"], ["web.access"],
       "Kayıtlarda görünen web sitesi adresi analiz sırasında açılmadı (alan adı çözülemedi, sayfa bulunamadı veya sunucu hata verdi). Bu geçici bir kesinti de olabilir.",
       "Açılmayan bir site, işletmeye ulaşmak isteyen kişiyi kaybettirebilir ve güveni zedeleyebilir. Geçici olup olmadığı görüşmeden önce kontrol edilmelidir.",
       "Mchttasarım siteyi kontrol eder; alan adı/barındırma sorununu çözer ya da gerekiyorsa siteyi yeniden kurar.",
       ["Adresi kendi tarayıcında (telefon ve bilgisayar) bir kez daha aç.", "Açılmıyorsa alan adının süresinin dolup dolmadığını öğren.", "İşletme sahibine siteyi kimin yaptığını ve yönetim erişiminin kimde olduğunu sor.", "Alan adı/barındırma bilgilerini iste ve teklif hazırla.", "Yenileme veya yeniden kurulum kapsamını belirle."],
       "Kayıtlı web adresiniz şu anda açılmıyor görünüyor; bu, size ulaşmak isteyen kişilerin siteye erişememesine yol açıyor olabilir. Adresi birlikte kontrol edip düzeltebiliriz.",
       "Web sitesi onarımı veya yenileme",
       ["Web sitenizin çalışmadığından haberiniz var mıydı?", "Siteyi kim hazırlamıştı, yönetim bilgileri sizde mi?", "Alan adınızın süresi ne zaman doluyor?"],
       ["Site tüm cihazlarda açılıyor mu?", "SSL (kilit simgesi) aktif mi?", "Alan adı yenileme tarihi not edildi mi?"]),

    _g("web_https", WEB, "HTTPS / güvenlik sorunu", ["Web Tasarım"], ["web.https"],
       "Site güvenli bağlantı (HTTPS) kullanmıyor ya da güvenlik sertifikası geçersiz görünüyor.",
       "Tarayıcılar 'güvenli değil' uyarısı gösterebilir; bu da ziyaretçi güvenini ve Google sıralamasını olumsuz etkileyebilir.",
       "Mchttasarım SSL sertifikasını kurar/yeniler, sitenin tüm adreslerini HTTPS'e yönlendirir.",
       ["Siteyi tarayıcıda aç, adres çubuğundaki uyarıyı ekran görüntüsüyle kaydet.", "Barındırma/alan adı erişimini iste.", "SSL sertifikası kur veya yenile.", "http adreslerini https'e yönlendir.", "Sayfaların karışık içerik uyarısı vermediğini kontrol et."],
       "Sitenizi açan kişilerin tarayıcısında güvenlik uyarısı görünüyor olabilir. Bu, ziyaretçinin siteden çıkmasına neden olabiliyor; kısa sürede düzeltebiliriz.",
       "Web sitesi güvenlik düzeltmesi (SSL/HTTPS)",
       ["Sitenizi açtığınızda bir güvenlik uyarısı görüyor musunuz?", "Barındırma hizmetini kimden alıyorsunuz?", "Sertifikanın bitiş tarihini takip eden biri var mı?"],
       ["Adres çubuğunda kilit simgesi var mı?", "http ile açılan adres https'e yönleniyor mu?", "Tüm sayfalar uyarısız açılıyor mu?"]),

    _g("web_mobil", WEB, "Mobil uyumluluk sorunu", ["Web Tasarım"], ["web.mobile"],
       "Sitede mobil ekrana uyum sağlayan temel ayar (viewport) bulunmadı; site telefonda masaüstü görünümünde, küçük açılıyor olabilir. (Not: yalnızca bu ayar kontrol edildi, gerçek cihaz testi yapılmadı.)",
       "Aramaların büyük bölümü telefondan yapılır; telefonda okunması zor bir site ziyaretçinin iletişime geçmeden ayrılmasına yol açabilir.",
       "Mchttasarım siteyi mobil uyumlu (responsive) olarak yeniler veya tasarımı düzeltir.",
       ["Siteyi kendi telefonunda aç ve ekran görüntüsü al.", "Yazıların okunup okunmadığını, butonların tıklanıp tıklanmadığını not et.", "Mevcut site altyapısını öğren (WordPress, hazır site vb.).", "Düzeltme mi yenileme mi gerektiğine karar ver.", "Teklifi hazırla; çalışma sonrası farklı telefonlarda test et."],
       "Web siteniz telefonda küçük/kullanışsız görünüyor olabilir. Müşterilerin çoğu sizi telefondan aradığı için sitenizin mobilde rahat kullanılması önemli.",
       "Mobil uyumlu web sitesi yenileme",
       ["Sitenizi telefonunuzdan hiç açıp baktınız mı?", "Müşterileriniz sizi çoğunlukla telefondan mı arıyor?", "Sitenizi en son ne zaman yenilediniz?"],
       ["Site iki farklı telefonda düzgün açılıyor mu?", "Menü, telefon ve harita butonları tek dokunuşla çalışıyor mu?", "Yazılar zoom yapmadan okunuyor mu?"]),

    _g("web_hiz", WEB, "Sayfa hızı yavaş", ["Web Tasarım"], ["web.speed"],
       "Ana sayfa yavaş yükleniyor olarak ölçüldü. (Ölçüm, bu sistemdeki bağlantıdan yapılan yaklaşık bir ölçümdür; kesin mobil hız testi değildir.)",
       "Yavaş açılan sayfalar ziyaretçinin siteden ayrılmasına ve arama sonuçlarında geride kalmaya yol açabilir.",
       "Mchttasarım görselleri küçültür, gereksiz kodu temizler ve barındırma/önbellek ayarlarını iyileştirir.",
       ["Siteyi farklı saatlerde iki kez aç, yavaşlığı doğrula.", "Görsellerin boyutunu ve eklenti/kod yoğunluğunu kontrol et.", "Barındırma paketini öğren.", "Hız iyileştirme kapsamını belirle ve teklif ver.", "Çalışma sonrası tekrar ölç."],
       "Sitenizin açılış hızı, ziyaretçilerin sabrını zorlayacak düzeyde olabilir. Birkaç teknik iyileştirmeyle daha hızlı açılmasını sağlayabiliriz.",
       "Web sitesi hız optimizasyonu",
       ["Sitenizin geç açıldığını hiç fark ettiniz mi?", "Sitede çok sayıda büyük görsel var mı?", "Barındırma hizmetini son ne zaman gözden geçirdiniz?"],
       ["Ana sayfa artık birkaç saniye içinde açılıyor mu?", "Görseller net ama küçük boyutta mı?", "Ölçüm öncesi/sonrası not edildi mi?"]),

    _g("web_title", WEB, "Title (sayfa başlığı) eksik veya yetersiz", ["Kurumsal SEO", "Yerel SEO"], ["web.title", "web.title_keywords"],
       "Title, Google sonuçlarında ve tarayıcı sekmesinde görünen sayfa başlığıdır. Sitede ya hiç yok, ya çok genel ('Ana Sayfa' gibi) ya da hizmet ve şehir bilgisini içermiyor.",
       "Arama sonucundaki ilk satır budur; işletmenin ne yaptığını ve nerede olduğunu anlatmıyorsa tıklanma ve sıralama şansı azalabilir.",
       "Mchttasarım işletme adı + ana hizmet + şehir/ilçe içeren, doğru uzunlukta başlıklar yazar ve sitede uygular.",
       ["Google'da '{kelime} {sehir}' araması yap ve işletmenin sitesinin sonuçta nasıl göründüğünü ekran görüntüsüyle kaydet.", "Site yönetim paneline veya site sahibine erişim iste.", "Ana hizmetleri ve hedef şehir/ilçeyi netleştir.", "Başlık önerisi yaz (ör. '{isletme} | {kelime} - {sehir}'), 50-60 karakteri geçme.", "Başlığı sitede güncelle.", "Birkaç gün sonra Google sonucunda görünümü kontrol et."],
       "Google'da {isletme} sonuçlarında görünen başlık, hizmetinizi ve bölgenizi net anlatmıyor olabilir. Başlığı düzenleyerek {sehir} bölgesinde {kelime} arayan kişilere daha doğru görünmenizi sağlayabiliriz.",
       "Kurumsal SEO / sayfa içi düzenleme",
       ["Google'da hangi kelimelerle bulunmak istiyorsunuz?", "Sitenizi en son kim güncelledi, yönetim erişimi sizde mi?", "Hizmet verdiğiniz bölgeler hangileri?"],
       ["Sayfa başlığı tarayıcı sekmesinde yeni haliyle görünüyor mu?", "Başlıkta hizmet ve şehir bilgisi var mı?", "Google'da yeniden taranınca sonuçta yeni başlık görünüyor mu?"]),

    _g("web_meta", WEB, "Meta description (arama sonucu açıklaması) eksik", ["Kurumsal SEO"], ["web.meta_description"],
       "Meta description, Google sonuçlarında başlığın altında görünen kısa açıklama metnidir. Sitede yok ya da çok kısa/uzun.",
       "Açıklama yoksa Google metni kendisi seçer; işletme mesajını kontrol edemez ve tıklanma oranı etkilenebilir.",
       "Mchttasarım hizmet, avantaj ve iletişim çağrısı içeren 140-160 karakterlik açıklamaları yazar ve uygular.",
       ["Sitenin önemli sayfalarını listele (ana sayfa, hizmetler, iletişim).", "Her sayfa için işletmenin gerçek hizmet/avantajlarına dayalı açıklama yaz.", "Açıklamaları site yönetiminden ekle.", "Uzunluğu kontrol et.", "Birkaç gün sonra Google sonucunda kontrol et."],
       "Google'da sitenizin altında görünen açıklama şu an eksik. Buraya hizmetlerinizi ve size ulaşma yolunu anlatan iki cümle eklemek, sonucu daha çekici hale getirebilir.",
       "Kurumsal SEO / sayfa içi düzenleme",
       ["Müşterilere sizi ilk anlatırken hangi cümleyi kullanıyorsunuz?", "Rakiplerinizden ayıran en önemli özelliğiniz ne?", "Sitede hangi sayfalar var?"],
       ["Ana sayfada meta description etiketi var mı?", "Uzunluk 70-170 karakter arasında mı?", "Metin gerçek hizmetleri anlatıyor mu?"]),

    _g("web_h1", WEB, "H1 (ana başlık) ve başlık yapısı sorunu", ["Kurumsal SEO"], ["web.h1", "web.heading_structure"],
       "Sayfada ana başlık (H1) yok veya alt başlıklar (H2/H3) kullanılmamış; içerik düzenli bölümlere ayrılmamış.",
       "Arama motorları sayfanın konusunu başlıklardan anlar; düzensiz yapı içeriğin doğru anlaşılmasını zorlaştırabilir.",
       "Mchttasarım sayfa başına tek bir açıklayıcı H1 ve mantıklı alt başlıklar düzenler.",
       ["Ana sayfayı aç ve sayfada görünen en büyük başlığı not et.", "Sayfanın konusunu tek cümlede belirle (hizmet + şehir).", "H1'i buna göre yaz; bölümlere H2 başlıkları ekle.", "Site yönetiminden uygula.", "Sayfayı kontrol edip görünüm bozulmadığını doğrula."],
       "Sayfanızın başlık düzeni, Google'ın sizi doğru konuyla ilişkilendirmesi için biraz eksik. Küçük bir düzenlemeyle bunu güçlendirebiliriz.",
       "Kurumsal SEO / içerik düzenleme",
       ["Ana sayfada müşteriye ilk söylemek istediğiniz şey nedir?", "Hangi hizmetler öne çıksın istersiniz?"],
       ["Sayfada tek bir H1 var mı?", "H1 hizmeti ve şehri anlatıyor mu?", "Alt başlıklar içeriği mantıklı bölüyor mu?"]),

    _g("web_seo_icerik", WEB, "SEO içerik eksikliği (az metin)", ["Kurumsal SEO", "Yerel SEO"], ["web.content_volume"],
       "Ana sayfada çok az yazı var. Google'ın işletmeyi hangi hizmetlerle ilişkilendireceğini anlaması için yeterli içerik bulunmuyor olabilir. (Site JavaScript ile çiziliyorsa bu ölçüm doğrulanamaz.)",
       "Az içerik, hizmet ve bölge aramalarında sitenin görünmesini zorlaştırabilir.",
       "Mchttasarım hizmet açıklamaları, sık sorulan sorular ve bölgeye özel içerik yazar.",
       ["Sitenin JavaScript ile çizilip çizilmediğini görüşmede teyit et.", "İşletmeden hizmet listesi, fiyat aralığı ve sık sorulan soruları iste.", "Her ana hizmet için ayrı sayfa/bölüm planla.", "İçerikleri yaz ve onaya sun.", "Yayına al, iç bağlantıları kontrol et."],
       "Sitenizde hizmetlerinizi anlatan yazı miktarı az görünüyor. Hizmetlerinizi ve bölgenizi anlatan içerikler eklemek, Google'da daha çok aramada karşınıza çıkmanıza yardımcı olabilir.",
       "Kurumsal SEO / içerik yazımı",
       ["Müşterilerin en çok sorduğu sorular neler?", "Hangi hizmetlerden en çok kazanıyorsunuz?", "Hizmet verdiğiniz mahalle/ilçeler hangileri?"],
       ["Ana hizmetlerin her biri için açıklama var mı?", "İçerikler özgün ve işletmeye ait mi?", "Sayfa yapısı düzenli mi?"]),

    _g("web_iletisim", WEB, "İletişim noktaları eksik / telefon tıklanabilir değil", ["Web Tasarım"], ["web.tel_link", "web.conversion"],
       "Sitede telefon numarası yok, ya da yazılı ama tıklanabilir bir arama bağlantısı değil; iletişim formu, WhatsApp veya randevu gibi kolay ulaşma yolları da sınırlı.",
       "Ziyaretçi kolayca ulaşamazsa müşteriye dönüşmeden ayrılabilir; mobilde numarayı elle çevirmek zorunda kalmak vazgeçmeye yol açabilir.",
       "Mchttasarım tıklanabilir telefon, WhatsApp, form ve harita butonlarını sitenin görünür yerlerine ekler.",
       ["Siteyi telefondan aç ve numaraya dokunmayı dene; sonucu not et.", "İşletmenin resmi telefon, WhatsApp ve e-posta bilgilerini teyit et.", "Sabit 'Ara' ve 'WhatsApp' butonu tasarla.", "İletişim formunu ekle veya düzenle.", "Test et: her buton doğru numaraya/adrese gidiyor mu?"],
       "Sitenizde numaranıza tek dokunuşla ulaşılamıyor olabilir. Ziyaretçiyi doğrudan arama yapmaya yönlendiren butonlar eklemek, ulaşan kişi sayısını artırabilir.",
       "Web sitesi iyileştirme (iletişim/dönüşüm butonları)",
       ["Müşterileriniz sizi en çok nasıl arıyor: telefon, WhatsApp, form?", "Sitenizden gelen aramaları takip ediyor musunuz?", "Hangi numara müşteri iletişimi için doğru numara?"],
       ["Mobilde numaraya dokununca arama ekranı açılıyor mu?", "WhatsApp butonu doğru numaraya gidiyor mu?", "Form test mesajı ulaştı mı?"]),

    _g("web_whatsapp", WEB, "WhatsApp bağlantısı yok", ["Web Tasarım"], ["web.whatsapp"],
       "Sitede WhatsApp ile yazışmayı başlatan bir bağlantı/buton bulunmadı.",
       "Türkiye'de müşteri iletişiminin önemli bir kısmı WhatsApp üzerinden yürür; buton yoksa bazı kişiler yazmadan vazgeçebilir.",
       "Mchttasarım sitenin her sayfasında görünen bir WhatsApp butonu ekler ve önceden yazılmış karşılama mesajı tanımlar.",
       ["İşletmenin WhatsApp Business numarasını ve mesai saatlerini öğren.", "Karşılama mesajını birlikte yaz.", "Butonu siteye ekle (telefonda sabit köşede).", "Test mesajı gönder.", "Yanıt sorumlusunu belirle."],
       "Müşterilerin size hızlıca yazabilmesi için sitenize bir WhatsApp butonu eklemek mümkün. Bu, telefonla arama yapmak istemeyenler için kolay bir ulaşma yolu sunar.",
       "Web sitesi iyileştirme (WhatsApp entegrasyonu)",
       ["Şu anda WhatsApp'tan müşteri mesajı alıyor musunuz?", "Mesajlara kim ve ne kadar sürede yanıt veriyor?"],
       ["Buton tüm sayfalarda görünüyor mu?", "Dokununca doğru numarada sohbet açılıyor mu?", "Karşılama mesajı doğru mu?"]),

    _g("web_local_seo", WEB, "Local SEO (yerel arama) eksikliği", ["Yerel SEO"], ["web.local_seo"],
       "Sitede şehir/ilçe adı başlık, ana başlık ve açıklamada belirgin biçimde geçmiyor; site 'bu işletme hangi bölgeye hizmet veriyor' bilgisini Google'a net vermiyor olabilir.",
       "Yerel aramalarda ('{kelime} {sehir}') bölgesel olarak ilgili görünmeyen site geride kalabilir.",
       "Mchttasarım şehir/ilçe odaklı başlıklar, hizmet-bölge sayfaları, adres/harita ve yerel schema ekler; Google İşletme Profiliyle uyumlu hale getirir.",
       ["Google'da '{kelime} {sehir}' araması yapıp işletmenin nerede çıktığını kaydet.", "Hizmet verilen ilçe/mahalleleri listele.", "Başlık, ana başlık ve açıklamaya bölge adını ekle.", "Ana hizmetler için bölgeye özel bölüm/sayfa oluştur.", "Adres ve harita bağlantısını ekle.", "Google İşletme Profilindeki bilgilerle tutarlılığı kontrol et."],
       "Sitenizde {sehir} bölgesi çok belirgin değil; bu yüzden Google'ın sizi yerel aramalarda öne çıkarması zorlaşabiliyor. Bölge odaklı düzenlemelerle bunu güçlendirebiliriz.",
       "Yerel SEO paketi",
       ["Müşterilerinizin çoğu hangi ilçelerden geliyor?", "Yeni müşteri getirmek istediğiniz bölgeler var mı?", "Google İşletme Profiliniz güncel mi?"],
       ["Başlıkta ve ana başlıkta şehir/ilçe geçiyor mu?", "Adres ve harita sitede görünüyor mu?", "Google'da yerel aramada sıralama takibe alındı mı?"]),

    _g("web_schema", WEB, "Schema (yapılandırılmış veri) eksik", ["Kurumsal SEO", "Yerel SEO"], ["web.schema"],
       "Sitede işletme bilgilerini (ad, adres, telefon, saat) arama motoruna makine diliyle anlatan 'LocalBusiness' verisi bulunmadı.",
       "Bu veri, Google'ın işletme bilgilerini daha doğru anlamasına ve bazı zengin sonuçlarda kullanmasına yardımcı olabilir; olmaması küçük ama giderilebilir bir eksiktir.",
       "Mchttasarım doğru işletme türüyle LocalBusiness schema kodunu hazırlar ve siteye ekler.",
       ["İşletmenin resmi ad, adres, telefon ve çalışma saatlerini teyit et.", "İşletme türüne uygun schema tipini belirle.", "Schema kodunu hazırla ve siteye ekle.", "Google'ın 'Zengin Sonuçlar Testi' aracıyla hata olmadığını kontrol et."],
       "Sitenizde işletme bilgilerinizi arama motoruna doğrudan anlatan teknik bir bölüm eksik. Ekleyerek bilgilerinizin Google'da daha doğru anlaşılmasına yardımcı olabiliriz.",
       "Kurumsal SEO / teknik SEO düzenlemesi",
       ["Adres ve telefon bilgileriniz güncel mi?", "Çalışma saatleriniz mevsime göre değişiyor mu?"],
       ["Schema testi hatasız mı?", "Bilgiler Google İşletme Profiliyle aynı mı?"]),

    _g("web_noindex", WEB, "Site Google'dan gizlenmiş (noindex)", ["Kurumsal SEO"], ["web.indexing"],
       "Sitenin ana sayfasında arama motorlarına 'beni listeleme' diyen bir ayar (noindex) bulundu. Bu bazen yayına alma öncesinde bilerek konur ve unutulur.",
       "Bu ayar açıkken site Google sonuçlarında hiç çıkmayabilir; işletme farkında olmadan arama trafiğini kaçırıyor olabilir.",
       "Mchttasarım ayarın kasıtlı olup olmadığını kontrol eder, gerekiyorsa kaldırır ve sitenin Google'a yeniden bildirilmesini sağlar.",
       ["İşletme sahibine siteyi Google'dan gizlemek isteyip istemediğini sor.", "Site yönetiminde 'arama motorlarından gizle' seçeneğini kontrol et.", "Ayarı kaldır.", "Site haritasını Google'a gönder.", "Birkaç gün sonra Google'da göründüğünü doğrula."],
       "Sitenizde Google'a 'beni gösterme' diyen bir ayar açık görünüyor. Bilerek yapılmadıysa, kapatmak sitenizin arama sonuçlarında görünmesini sağlayabilir.",
       "Kurumsal SEO / teknik düzeltme",
       ["Siteyi bilerek Google'dan gizlemiş miydiniz?", "Siteniz yeni mi yayına alındı?"],
       ["Sayfa kaynağında noindex kalktı mı?", "Google'da site adı aratınca sonuç çıkıyor mu?"]),

    _g("web_sitemap", WEB, "Site haritası (sitemap.xml) yok", ["Kurumsal SEO"], ["web.sitemap"],
       "Sitede Google'a tüm sayfaları listeleyen site haritası dosyası bulunmadı.",
       "Site haritası Google'ın sayfaları keşfetmesini kolaylaştırır; özellikle yeni ve derindeki sayfalar için faydalıdır.",
       "Mchttasarım site haritasını oluşturur ve Google Search Console'a gönderir.",
       ["Site altyapısını öğren.", "Site haritasını oluştur (eklenti veya elle).", "sitemap.xml adresini test et.", "Google Search Console'a gönder."],
       "Sitenizin tüm sayfalarını Google'a düzenli bildiren bir harita dosyası yok. Bunu eklemek küçük ama faydalı bir teknik iyileştirme.",
       "Kurumsal SEO / teknik SEO",
       ["Google Search Console erişiminiz var mı?", "Sitede kaç sayfa var?"],
       ["/sitemap.xml açılıyor mu?", "Search Console'da gönderildi ve okundu mu?"]),

    _g("web_olcum", WEB, "Ziyaretçi ölçümü / reklam etiketi yok (Analytics, Etiket Yöneticisi)", ["Kurumsal SEO", "Google Ads"], ["web.analytics"],
       "Sitede Google Analytics, Google Etiket Yöneticisi, Google Ads dönüşüm etiketi veya Meta Pixel bulunmadı.",
       "Ölçüm yoksa sitenin kaç kişi getirdiği ve hangi işlemlerin müşteri kazandırdığı bilinmez; Google Ads gibi reklam yatırımları ölçülemez ve iyileştirilemez.",
       "Mchttasarım Analytics ve Etiket Yöneticisi'ni kurar, arama/WhatsApp/form dönüşümlerini takip eder; istenirse Google Ads kampanyasını bu ölçüme bağlar.",
       ["Mevcut Google hesaplarına erişimi teyit et.", "Analytics (GA4) mülkünü ve Etiket Yöneticisi'ni kur.", "Telefon tıklaması, WhatsApp ve form gönderimini dönüşüm olarak tanımla.", "Search Console'u bağla.", "Birkaç gün sonra verinin aktığını doğrula."],
       "Sitenize kaç kişinin geldiğini ve kaçının sizi aradığını şu an göremiyorsunuz. Ölçümü kurarsak hangi çalışmanın müşteri getirdiğini net görürsünüz; reklam vermek isterseniz de bütçeyi doğru yere harcarsınız.",
       "Analytics/dönüşüm takibi kurulumu + Google Ads",
       ["Sitenizin ziyaretçi sayısını takip ediyor musunuz?", "Şu an Google'da reklam veriyor musunuz?", "Google Analytics hesabınıza kim sahip?"],
       ["Analytics'te gerçek zamanlı ziyaretçi görünüyor mu?", "Telefon/WhatsApp tıklamaları dönüşüm olarak kaydediliyor mu?"]),

    _g("web_cta", WEB, "Belirgin harekete geçirici çağrı (CTA) yok", ["Web Tasarım"], ["web.cta"],
       "Ana sayfada 'Hemen Ara', 'Randevu Al', 'Teklif Al' gibi belirgin bir çağrı bulunmadı.",
       "Ziyaretçiye ne yapması gerektiği söylenmezse ilgi müşteriye dönüşmeden sayfadan ayrılır.",
       "Mchttasarım ana sayfaya ve hizmet sayfalarına görünür arama/WhatsApp/randevu butonları ekler.",
       ["Hedef eylemi belirle (arama, randevu, teklif).", "Sayfa başına tek net çağrı tasarla.", "Mobilde sabit arama/WhatsApp düğmesi ekle.", "Tıklamaları ölç."],
       "Sitenizde ziyaretçiyi 'şimdi arayın' veya 'randevu alın' diye yönlendiren belirgin bir düğme yok. Bunu eklemek ziyaretçi-müşteri dönüşümünü artırabilir.",
       "Web sitesi iyileştirme",
       ["Siteden en çok hangi eylemi bekliyorsunuz?", "Şu an siteden kaç arama/randevu geliyor?"],
       ["Ana sayfada üstte belirgin çağrı düğmesi var mı?", "Mobilde çağrı düğmesi kolay tıklanıyor mu?"]),

    _g("web_ic_link", WEB, "İç bağlantı yapısı zayıf", ["Kurumsal SEO"], ["web.internal_links"],
       "Ana sayfadan diğer sayfalara giden bağlantı sayısı çok az; site tek sayfa gibi çalışıyor.",
       "İç bağlantılar ziyaretçiyi hizmet sayfalarına taşır ve Google'ın siteyi keşfetmesine yardımcı olur.",
       "Mchttasarım site yapısını hizmet sayfaları ve doğru iç bağlantılarla planlar.",
       ["Sayfa haritasını çıkar.", "Ana hizmetler için ayrı sayfalar planla.", "Menü ve sayfa içi bağlantıları ekle.", "Kırık bağlantı kontrolü yap."],
       "Sitenizde sayfalar arası yönlendirme çok az. Hizmetlerinize ayrı sayfalar ve doğru bağlantılar eklersek hem ziyaretçi hem Google için daha anlaşılır olur.",
       "Kurumsal SEO / site yapısı",
       ["Hangi hizmetler için ayrı sayfa istersiniz?", "Sitede en çok hangi sayfa ziyaret ediliyor?"],
       ["Menüde ana hizmetlere bağlantı var mı?", "Yeni sayfalar Google'da dizinleniyor mu?"]),

    _g("web_rakip_icerik", WEB, "Rakiplerin çoğunda olan içerik/özellikler sitede yok", ["Web Tasarım", "Kurumsal SEO"], ["web.peer_gap"],
       "Aynı bölge ve sektördeki analiz edilmiş rakip sitelerin çoğunda bulunan bazı içerik/özellikler bu sitede yok.",
       "Rakiplerin çoğunun sunduğu içerik ve özellikler müşterinin beklentisi haline gelir; eksikliği rakibe geçişi kolaylaştırır.",
       "Mchttasarım eksik içerik ve özellikleri (ör. hizmet sayfaları, WhatsApp, randevu formu) rakip düzeyine getirecek şekilde planlar.",
       ["Rakip karşılaştırma tablosunu incele.", "Eksik özellikleri önceliklendir.", "İçerik ve tasarımı hazırla.", "Yayına al ve ölç."],
       "Bölgenizdeki benzer işletmelerin çoğunda olan bazı özellikler sitenizde yok. Bunları tamamlayarak rakiplerin gerisinde kalmayabilirsiniz.",
       "Web sitesi iyileştirme + Kurumsal SEO",
       ["Rakip sitelerine hiç baktınız mı?", "Müşteriler size neden başka firmaları tercih ettiklerini söylüyor mu?"],
       ["Eksik özellikler eklendi mi?", "Rakip karşılaştırması yeniden yapıldığında fark kapandı mı?"]),

    _g("web_harita", WEB, "Sitede harita / konum bağlantısı yok", ["Web Tasarım", "Yerel SEO"], ["web.maps_link"],
       "Sitede Google Haritalar bağlantısı veya gömülü harita bulunmadı.",
       "Fiziksel mekânı olan işletmede ziyaretçinin yol tarifi alabilmesi, müşteriyi kapıya getirmede önemlidir.",
       "Mchttasarım iletişim sayfasına ve alt bilgiye harita ile 'Yol tarifi al' butonu ekler.",
       ["İşletmenin Google Haritalar bağlantısını teyit et.", "Haritayı iletişim sayfasına göm.", "Ana sayfaya 'Yol tarifi' butonu ekle.", "Mobilde test et."],
       "Sitenizde konumunuzu gösteren bir harita ve yol tarifi butonu eksik. Ekleyerek size gelmek isteyenlerin işini kolaylaştırabiliriz.",
       "Web sitesi iyileştirme",
       ["Müşteriler adresinizi bulmakta zorlanıyor mu?", "Mekânınıza park/erişim nasıl?"],
       ["Harita doğru konumu gösteriyor mu?", "Yol tarifi butonu Google Haritalar'ı açıyor mu?"]),

    _g("web_randevu", WEB, "Online randevu / rezervasyon yok", ["Web Tasarım"], ["web.booking"],
       "Sitede randevu veya rezervasyon almaya yarayan bağlantı ya da form bulunmadı.",
       "Bu sektörde müşteriler randevu/rezervasyon yapmak ister; online seçenek yoksa mesai dışındaki talepler kaçabilir (bazı işletmeler bilerek yalnızca telefonla çalışır).",
       "Mchttasarım siteye randevu/rezervasyon formu veya takvim entegrasyonu ekler.",
       ["İşletmenin randevu/rezervasyon sürecini öğren.", "Online randevu isteyip istemediğini sor.", "Form veya takvim çözümünü seç.", "Bildirimlerin kime gideceğini belirle.", "Test randevusu al."],
       "Sitenizden randevu/rezervasyon alma imkânı görünmüyor. Mesai dışında da talep toplayabileceğiniz basit bir form ekleyebiliriz.",
       "Web sitesi iyileştirme (randevu/rezervasyon formu)",
       ["Randevuları şimdi nasıl alıyorsunuz?", "Mesai dışında gelen talepleri nasıl karşılıyorsunuz?"],
       ["Form test kaydı size ulaştı mı?", "Müşteriye onay mesajı gidiyor mu?"]),

    _g("web_hizmet_sayfalari", WEB, "Hizmet / hakkımızda / referans sayfaları eksik", ["Web Tasarım", "Kurumsal SEO"], ["web.services_page", "web.about", "web.references"],
       "Sitede hizmetleri, işletmeyi tanıtan (hakkımızda) veya örnek çalışmaları/yorumları gösteren sayfa bağlantıları bulunmadı.",
       "Ziyaretçi neyi, kimden alacağını göremezse karar vermekte zorlanabilir; ayrı hizmet sayfaları hizmete özel aramalarda görünmeye de yardımcı olur.",
       "Mchttasarım eksik sayfaları planlar, içeriklerini yazar ve menüye ekler.",
       ["Mevcut menüyü ve sayfaları listele.", "İşletmenin ana hizmetlerini ve öne çıkan özelliklerini topla.", "Her ana hizmet için ayrı sayfa planla.", "Hakkımızda ve (varsa) referans/galeri içeriklerini iste.", "Sayfaları hazırla ve menüye bağla."],
       "Sitenizde hizmetlerinizi ve sizi tanıtan sayfalar sınırlı görünüyor. Bunları tamamlamak, ziyaretçinin karar vermesini kolaylaştırabilir.",
       "Web sitesi geliştirme (hizmet/kurumsal sayfalar)",
       ["Hangi hizmetlerinizi öne çıkarmak istersiniz?", "Gurur duyduğunuz bir çalışma/müşteri yorumu var mı?"],
       ["Menüde hizmetler ve hakkımızda görünüyor mu?", "Her sayfada iletişim butonu var mı?"]),

    _g("web_blog", WEB, "Blog / içerik bölümü yok", ["Kurumsal SEO"], ["web.blog"],
       "Sitede blog, makale veya haber bölümü bulunmadı.",
       "Düzenli içerik, sitenin Google'dan ziyaretçi çekmesinin yollarından biridir; zorunlu bir eksik değil, bir fırsattır.",
       "Mchttasarım işletmenin uzmanlık alanına uygun içerik planı hazırlar ve düzenli yazılar üretir.",
       ["İşletmenin sık sorulan sorularını ve uzmanlık konularını topla.", "Aylık içerik planı hazırla.", "İlk yazıları yaz ve yayınla.", "Yazıları sosyal medya ile paylaş."],
       "Sitenizde müşterilerin sık sorduğu soruları yanıtlayan yazılar yok. Bu tür içerikler Google'dan ek ziyaretçi getirebilir.",
       "Kurumsal SEO / içerik pazarlaması",
       ["Müşteriler en çok hangi soruları soruyor?", "Ayda kaç içerik yayınlanması gerçekçi olur?"],
       ["İçerikler yayında mı?", "Yazılar hizmet ve bölge ile ilişkili mi?"]),

    _g("web_gorsel", WEB, "Görsel alt metinleri eksik / görsel yok", ["Kurumsal SEO", "Grafik Tasarım"], ["web.images"],
       "Sitedeki görsellerin çoğunda açıklama (alt) metni yok veya sitede hiç görsel bulunmadı.",
       "Alt metin görselin Google tarafından anlaşılmasına ve ekran okuyucu kullanan ziyaretçilere yardımcı olur; görselsiz site de profesyonellik algısını düşürebilir.",
       "Mchttasarım görsellere anlamlı alt metinler ekler; gerekirse profesyonel görsel/fotoğraf hazırlar.",
       ["Sitedeki görselleri listele.", "Her görsel için kısa, açıklayıcı bir metin yaz.", "Alt metinleri siteye gir.", "Görselleri boyut ve netlik bakımından kontrol et."],
       "Sitenizdeki görsellerin çoğu Google'a ne olduklarını anlatmıyor. Küçük düzenlemeyle hem görünürlüğü hem erişilebilirliği artırabiliriz.",
       "Kurumsal SEO / görsel optimizasyonu",
       ["Sitede kullanılan fotoğraflar size mi ait?", "Yeni fotoğraf çekimi düşünür müsünüz?"],
       ["Görsellerde alt metin dolu mu?", "Görseller hızlı yükleniyor mu?"]),

    _g("web_kirik_link", WEB, "Kırık bağlantılar", ["Web Tasarım"], ["web.broken_links"],
       "Sitedeki bazı iç bağlantılar açılmıyor (sayfa bulunamadı gibi).",
       "Kırık bağlantılar ziyaretçiyi hayal kırıklığına uğratır ve sitenin bakımsız görünmesine yol açabilir.",
       "Mchttasarım kırık bağlantıları bulup düzeltir veya doğru sayfaya yönlendirir.",
       ["Analizde listelenen kırık adresleri not et.", "Sayfanın taşınıp taşınmadığını öğren.", "Bağlantıları düzelt veya yönlendirme ekle.", "Tüm menüyü tıklayarak kontrol et."],
       "Sitenizde tıklandığında açılmayan bağlantılar var. Bunları düzeltmek siteyi daha güvenilir gösterir.",
       "Web sitesi bakım/onarım",
       ["Sitede yakın zamanda sayfa taşıma/silme yaptınız mı?", "Siteyi kim yönetiyor?"],
       ["Düzeltilen bağlantılar doğru sayfayı açıyor mu?", "Yeni kırık bağlantı kaldı mı?"]),

    _g("web_guncel", WEB, "Site güncel görünmüyor", ["Web Tasarım"], ["web.freshness"],
       "Sitenin alt bilgisindeki telif yılı eski; site uzun süredir güncellenmemiş olabilir. (Yalnızca bu göstergeye bakıldı.)",
       "Güncel görünmeyen site güveni azaltabilir; eski altyapılar mobil ve hız sorunlarına da yol açabilir.",
       "Mchttasarım siteyi gözden geçirir; küçük güncelleme mi yenileme mi gerektiğini belirler.",
       ["Siteyi açıp içerik ve tasarımın güncelliğini değerlendir.", "Fiyat, telefon, saat gibi bilgilerin doğruluğunu kontrol et.", "Güncelleme veya yenileme önerisi hazırla."],
       "Sitenizin bazı bölümleri uzun süredir güncellenmemiş görünüyor. Güncel bilgi ve görünüm müşteriye güven verir.",
       "Web sitesi yenileme / güncelleme",
       ["Sitenizi son ne zaman güncellediniz?", "Bilgilerde değişen bir şey var mı?"],
       ["Telif yılı ve içerikler güncel mi?", "Tüm iletişim bilgileri doğru mu?"]),

    _g("web_eticaret", WEB, "Online satış altyapısı yok", ["E-Ticaret"], ["web.ecommerce"],
       "Ürün satan bir işletme için sitede sepet/online satış işareti bulunmadı.",
       "Mağaza dışındaki müşteriler ürünü başka sitelerden alıyor olabilir. (Satışın bilerek yalnızca mağazada yapılıyor olması da mümkündür.)",
       "Mchttasarım ürün kataloğu, sepet, ödeme ve kargo entegrasyonuyla e-ticaret sitesi kurar.",
       ["İşletmenin online satmak isteyip istemediğini öğren.", "Ürün sayısını ve fiyat/stok yönetimini sor.", "Ödeme ve kargo tercihlerini belirle.", "Kapsam ve teklif hazırla.", "İlk ürünlerle test satışı yap."],
       "Ürünlerinizi internetten de satabileceğiniz bir altyapı görünmüyor. Mağaza dışındaki müşterilere de ulaşmanızı sağlayabiliriz.",
       "E-ticaret sitesi kurulumu",
       ["Ürünlerinizi şu an internette satıyor musunuz?", "Kargo ile satış yapmayı düşünür müsünüz?", "Kaç çeşit ürününüz var?"],
       ["Test siparişi tamamlandı mı?", "Ödeme ve kargo bildirimleri çalışıyor mu?"]),

    _g("web_spam", WEB, "Sitede şüpheli / spam içerik (ele geçirilmiş olabilir)", ["Web Tasarım", "Kurumsal SEO"], ["web.spam_content"],
       "Kayıtlı sitede işletmeyle ilgisiz, şüpheli (spam/yetişkin/bahis benzeri) ifadeler görüldü. Site ele geçirilmiş ya da alan adı başka birine geçmiş olabilir; kesin nedeni doğrulanmalıdır.",
       "Böyle bir içerik müşteri güvenini ve Google sıralamasını ciddi biçimde olumsuz etkileyebilir; acil müdahale gerektirir.",
       "Mchttasarım siteyi temizler, güvenliğini sağlar veya yeni ve güvenli bir kurumsal site kurar.",
       ["Adresi işletme sahibiyle birlikte aç ve gördüğünüz içeriği ekran görüntüsüyle kaydet.", "Alan adının işletmeye ait olup olmadığını ve yönetim erişimini kimin tuttuğunu öğren.", "Güvenli bir yedek/yeni site planı yap.", "Şifreleri değiştirt ve siteyi temizle/yeniden kur.", "Yayın sonrası Google'dan temizlenme sürecini takip et."],
       "Kayıtlı web adresinizde işletmenizle ilgisiz içerik görünüyor; site ele geçirilmiş olabilir. Bu durum güveninizi etkileyebileceği için acil kontrol etmenizi ve güvenli bir site kurmanızı öneririz.",
       "Site temizleme ve yeni kurumsal web sitesi",
       ["Bu adreste gördüğümüz içerik size mi ait?", "Alan adını ve siteyi kim yönetiyor?", "Son zamanlarda şifre veya barındırma değişikliği oldu mu?"],
       ["Site temiz ve güvenli mi?", "Tarayıcı uyarısı kalktı mı?", "Yönetim şifreleri değiştirildi mi?"]),

    _g("web_marka_uyumsuz", WEB, "Kayıtlı site işletmeyle uyumsuz görünüyor", ["Kurumsal Web Sitesi", "Web Tasarım"], ["web.brand_match"],
       "Kayıtlardaki web sitesinde işletmenin adı geçmiyor; adres başka bir firmaya ait ya da yanlış girilmiş olabilir.",
       "Yanlış adres müşteriyi başka bir yere yönlendirir ve işletmenin dijital varlığının eksik görünmesine yol açabilir.",
       "Mchttasarım işletmenin gerçek sitesini doğrular; yoksa kurumsal bir site kurar ve Google profiliyle bağlar.",
       ["Adresi işletme sahibiyle birlikte aç ve işletmenin sitesi olup olmadığını sor.", "Gerçek bir siteleri varsa adresini al.", "Yoksa web sitesi kapsamını planla.", "Google İşletme Profilindeki bağlantıyı doğru adrese güncelle."],
       "Kayıtlı web adresinizde işletmenizle ilgili bir içerik göremedik. Doğru ve size ait bir site, müşterilerin sizi bulmasını kolaylaştırır.",
       "Kurumsal web sitesi + Google profil bağlantısı",
       ["Bu adres sizin sitenize mi ait?", "Kendi sitenizi kim hazırlamıştı?"],
       ["Google profilindeki site bağlantısı doğru adresi gösteriyor mu?", "Site işletme adını ve iletişim bilgilerini içeriyor mu?"]),

    # =============================================================== GOOGLE İŞLETME PROFİLİ
    _g("gbp_profil_yok", GBP, "Google İşletme Profili bulunamadı", ["Google İşletme Profili Optimizasyonu"], ["gbp.profile_found"],
       "Google Haritalar'da bu işletmeyle güvenle eşleşen bir profil bulunamadı. (Farklı adla kayıtlı bir profil olabilir; görüşmede teyit edilmelidir.)",
       "Google Haritalar'da görünmeyen işletme 'yakınımdaki ...' aramalarında çıkmayabilir ve yorum/puan toplayamayabilir.",
       "Mchttasarım profili oluşturur, doğrulama sürecini yönetir ve eksiksiz doldurur.",
       ["Google Haritalar'da işletmeyi elle ara (ad, telefon, adres).", "Varsa mevcut profili sahiplen; yoksa yeni profil hazırla.", "Kategori, adres, telefon, saat, açıklama ve fotoğrafları topla.", "Google doğrulama adımını (kartpostal/telefon/video) yönet.", "Profil yayına girince bilgileri kontrol et."],
       "Google Haritalar'da işletmenize ait bir profil bulamadık. Profil oluşturmak, bölgenizde arama yapanlara görünmenin en hızlı yollarından biri.",
       "Google İşletme Profili kurulumu ve optimizasyonu",
       ["Google'da işletmenizin bir profili var mı, yöneten kim?", "Profil doğrulama için telefon/adres erişiminiz var mı?"],
       ["Profil Google Haritalar'da görünüyor mu?", "Bilgiler doğru ve eksiksiz mi?"]),

    _g("gbp_kategori", GBP, "Kategori problemi", ["Google İşletme Profili Optimizasyonu"], ["gbp.primary_category", "gbp.extra_categories"],
       "Profildeki ana kategori eksik ya da işletmenin sektörüyle uyumsuz görünüyor; ek kategoriler de sınırlı olabilir.",
       "Kategori, hangi aramalarda görüneceğinizi belirleyen en önemli alandır; yanlış kategori doğru müşterilerin sizi görmesini engelleyebilir.",
       "Mchttasarım doğru ana kategoriyi seçer, uygun ek kategorileri ekler ve hizmetlerle uyumlu hale getirir.",
       ["Profilde görünen ana kategoriyi not et.", "İşletmenin asıl gelir getiren hizmetlerini öğren.", "En uygun ana ve ek kategorileri belirle.", "Profil sahibiyle kategori değişikliğini yap.", "Birkaç hafta içinde görünürlük değişimini izle."],
       "Google profilinizdeki kategori, verdiğiniz hizmetleri tam yansıtmıyor olabilir. Doğru kategori, doğru müşterinin sizi bulmasına yardımcı olur.",
       "Google İşletme Profili optimizasyonu",
       ["Ağırlıklı olarak hangi hizmetlerden kazanıyorsunuz?", "Google profilini yönetme yetkisi kimde?"],
       ["Ana kategori hizmetle uyumlu mu?", "Ek kategoriler eklendi mi?"]),

    _g("gbp_hizmetler", GBP, "Hizmet / özellik bilgileri eksik", ["Google İşletme Profili Optimizasyonu"], ["gbp.services_list"],
       "Profilin 'Hakkında' bölümünde hizmet seçenekleri veya özellikler bulunamadı. (Bazı alanlar Google'ın oturumsuz görünümünde okunamayabilir.)",
       "Hizmet ve özellikler profili zenginleştirir ve müşterinin karar vermesini kolaylaştırabilir.",
       "Mchttasarım profildeki hizmet, ürün ve özellik alanlarını eksiksiz doldurur.",
       ["Profildeki mevcut hizmet/özellik alanlarını kontrol et.", "İşletmeden hizmet listesi ve kısa açıklamalarını iste.", "Profile hizmetleri ve özellikleri gir.", "Yayında göründüğünü kontrol et."],
       "Google profilinizde hizmetlerinizi ve özelliklerinizi anlatan bölümler eksik. Doldurmak profilin daha güven verici görünmesine yardımcı olabilir.",
       "Google İşletme Profili optimizasyonu",
       ["Verdiğiniz tüm hizmetlerin listesi nedir?", "Öne çıkan özellikleriniz (ör. eve servis, otopark) neler?"],
       ["Hizmet ve özellik alanları dolu mu?", "Bilgiler siteyle tutarlı mı?"]),

    _g("gbp_aciklama", GBP, "İşletme açıklaması eksik", ["Google İşletme Profili Optimizasyonu"], ["gbp.description"],
       "Profilde işletmeyi anlatan açıklama metni bulunamadı.",
       "Açıklama, işletmenin ne yaptığını ve neden tercih edilmesi gerektiğini anlatan alandır; boşsa profil yeterince tanıtıcı olmayabilir.",
       "Mchttasarım anahtar kelimelerle uyumlu, doğru ve abartısız bir açıklama yazıp profile ekler.",
       ["İşletmenin kuruluş yılı, uzmanlığı ve hizmetleri hakkında bilgi topla.", "750 karakteri aşmayan açıklamayı yaz.", "İşletme sahibinden onay al.", "Profile ekle."],
       "Google profilinizde işletmenizi tanıtan bir açıklama yok. Kısa ve doğru bir açıklama, sizi arayan kişiye ilk izlenimi güçlendirebilir.",
       "Google İşletme Profili optimizasyonu",
       ["İşletmenizi tek cümleyle nasıl anlatırsınız?", "Sizi diğerlerinden ayıran nedir?"],
       ["Açıklama profilde görünüyor mu?", "Bilgiler gerçek ve güncel mi?"]),

    _g("gbp_foto", GBP, "Fotoğraf eksikliği / eski fotoğraf", ["Fotoğraf ve Video İçerik", "Google İşletme Profili Optimizasyonu"], ["gbp.photos", "gbp.last_photo"],
       "Profilde yeterli/güncel fotoğraf görünmüyor (ör. kapak fotoğrafı eski tarihli). (Fotoğraf sayısı Google'ın oturumsuz görünümünde okunamayabilir.)",
       "Fotoğraf, profilin en dikkat çeken bölümüdür; az veya eski fotoğraf profili bakımsız gösterebilir ve tıklanmayı azaltabilir.",
       "Mchttasarım profesyonel mekân/ekip/ürün fotoğrafı ve kısa video çekimi yapıp profile yükler.",
       ["Profildeki mevcut fotoğrafları birlikte incele.", "Çekim planı yap: dış cephe, iç mekân, ekip, ürün/hizmet.", "Çekim gününü belirle.", "Fotoğrafları düzenle ve profile yükle.", "Düzenli fotoğraf ekleme takvimi oluştur."],
       "Google profilinizdeki fotoğraflar sınırlı/eski görünüyor. Yeni ve kaliteli fotoğraflar profilinizi daha davetkâr yapabilir.",
       "Profesyonel fotoğraf/video çekimi + profil güncelleme",
       ["Mekânın güncel fotoğrafları var mı?", "Profesyonel çekim için uygun bir gün var mı?"],
       ["Yeni fotoğraflar profilde yayında mı?", "Kapak fotoğrafı güncel mi?"]),

    _g("gbp_yorum_az", GBP, "Yorum sayısı düşük", ["Google İşletme Profili Optimizasyonu"], ["gbp.review_count"],
       "Profildeki Google yorum sayısı düşük ya da benzer işletmelerin gerisinde.",
       "Yorum sayısı güveni ve Google Haritalar sıralamasını etkileyebilir; müşteriler az yorumlu işletmeyi tercih etmekte tereddüt edebilir.",
       "Mchttasarım memnun müşterilerden yorum toplamak için QR kodlu kart/mesaj sistemi ve yorum isteme süreci kurar.",
       ["Profilin yorum bağlantısını (kısa link) oluştur.", "QR kodlu basılı kart veya mesaj şablonu hazırla.", "Personele yorum isteme sürecini anlat (memnun müşteriye nazikçe).", "Yorumların takibi için haftalık kontrol belirle."],
       "Google'da yorum sayınız benzer işletmelere göre az görünüyor. Memnun müşterilerinizden yorum toplamayı kolaylaştıran basit bir sistem kurabiliriz.",
       "Google İşletme Profili optimizasyonu + yorum toplama kartı",
       ["Memnun müşterilerinizden yorum istiyor musunuz?", "Müşterilerle iletişim kurduğunuz bir kanal var mı (WhatsApp, SMS)?"],
       ["Yeni yorum sayısı düzenli artıyor mu?", "Yorum bağlantısı/QR çalışıyor mu?"]),

    _g("gbp_yorum_cevap", GBP, "Yorumlara cevap verilmemiş", ["Google İşletme Profili Optimizasyonu", "Sosyal Medya Yönetimi"], ["gbp.review_replies"],
       "İncelenen son yorumların çoğuna işletme yanıtı verilmemiş görünüyor.",
       "Yorumlara nazik yanıt vermek işletmenin ilgili olduğunu gösterir ve güveni destekleyebilir.",
       "Mchttasarım yorum yanıt şablonları hazırlar ve düzenli yanıt sürecini üstlenir/yönetir.",
       ["Yanıtsız yorumları listele.", "Olumlu ve olumsuz yorumlar için yanıt şablonları yaz.", "Yanıtları işletme sahibi onayıyla yayınla.", "Haftalık yanıt rutini oluştur."],
       "Google'daki yorumların çoğu yanıtsız görünüyor. Kısa ve nazik yanıtlar hem yorum yazana hem profili inceleyene olumlu bir izlenim verir.",
       "Google İşletme Profili yönetimi (yorum yanıtlama)",
       ["Yorumları kim takip ediyor?", "Olumsuz bir yoruma nasıl yanıt vermek istersiniz?"],
       ["Son yorumların çoğuna yanıt verildi mi?", "Yanıtlar nazik ve doğru mu?"]),

    _g("gbp_saat", GBP, "Çalışma saatleri eksik", ["Google İşletme Profili Optimizasyonu"], ["gbp.hours"],
       "Profilde çalışma saatleri girilmemiş.",
       "Saat bilgisi olmayan profil 'şu an açık mı?' sorusunu cevaplayamaz; müşteri boşuna gelmekten çekinebilir.",
       "Mchttasarım haftalık saatleri, resmî tatil ve özel gün saatlerini profile girer.",
       ["İşletmenin haftalık çalışma saatlerini öğren.", "Özel gün/tatil saatlerini sor.", "Profile gir.", "Kontrol et."],
       "Google profilinizde çalışma saatleri görünmüyor. Doğru saatler, müşterinin size ne zaman gelebileceğini net gösterir.",
       "Google İşletme Profili optimizasyonu",
       ["Çalışma saatleriniz nedir?", "Resmî tatillerde açık mısınız?"],
       ["Saatler profilde doğru görünüyor mu?"]),

    _g("gbp_web", GBP, "Profilde web sitesi bağlantısı yok", ["Kurumsal Web Sitesi", "Google İşletme Profili Optimizasyonu"], ["gbp.website"],
       "Google profilinde web sitesi alanı boş.",
       "Profildeki web bağlantısı, Google'dan gelen ziyaretçinin ilk durağıdır; boşsa ziyaretçi daha fazla bilgiye ulaşamayabilir.",
       "Mchttasarım varsa mevcut siteyi profile bağlar; yoksa kurumsal web sitesi kurar.",
       ["İşletmenin bir web sitesi olup olmadığını sor.", "Varsa adresini profile ekle.", "Yoksa web sitesi teklifi hazırla."],
       "Google profilinizde web sitenize giden bir bağlantı görünmüyor. Bağlantı eklemek veya yeni bir site kurmak, ziyaretçiyi doğru bilgiye yönlendirir.",
       "Kurumsal web sitesi + profil bağlantısı",
       ["Web siteniz var mı, adresi nedir?"],
       ["Profildeki bağlantı doğru siteyi açıyor mu?"]),

    _g("gbp_telefon", GBP, "Profilde telefon numarası yok", ["Google İşletme Profili Optimizasyonu"], ["gbp.phone"],
       "Google profilinde telefon numarası görünmüyor.",
       "Telefon yoksa arayan müşteri tek dokunuşla ulaşamaz.",
       "Mchttasarım doğru telefonu profile ekler.",
       ["Müşteri iletişim numarasını teyit et.", "Profile ekle.", "Aramayı test et."],
       "Google profilinizde arayabileceğimiz/arayabilecekleri bir numara görünmüyor. Eklemek müşterinin size ulaşmasını kolaylaştırır.",
       "Google İşletme Profili optimizasyonu",
       ["Müşteriler sizi hangi numaradan arasın istersiniz?"],
       ["Numara profilde görünüyor ve tıklanınca arıyor mu?"]),

    _g("gbp_puan", GBP, "Google puanı düşük", ["Google İşletme Profili Optimizasyonu"], ["gbp.rating"],
       "Profilin ortalama puanı düşük görünüyor.",
       "Düşük puan, müşterinin işletmeyi seçmesini zorlaştırabilir.",
       "Mchttasarım yorumlardaki tekrarlayan şikâyetleri analiz eder, yanıt stratejisi ve memnun müşteriden yorum toplama sistemi kurar.",
       ["Olumsuz yorumları oku ve tekrar eden konuları not et.", "İşletme sahibiyle nedenleri konuş.", "Nazik yanıtlar yaz.", "Memnun müşteri yorumu toplama sürecini başlat."],
       "Google puanınız beklenenden düşük görünüyor. Yorumlara profesyonelce yanıt vermek ve memnun müşterilerin yorum yazmasını kolaylaştırmak puanı toparlamaya yardımcı olabilir.",
       "Google İşletme Profili yönetimi",
       ["Olumsuz yorumların ortak nedeni ne?", "Bu konuda iyileştirme yapıldı mı?"],
       ["Yeni yorumların puan ortalaması yükseliyor mu?"]),

    _g("gbp_yorum_akisi", GBP, "Yorum akışı durmuş görünüyor", ["Google İşletme Profili Optimizasyonu"], ["gbp.last_review"],
       "İncelenen en yeni yorum oldukça eski görünüyor (Google göreli tarih verdiği için yaklaşık).",
       "Uzun süredir yorum almayan profil aktif görünmeyebilir.",
       "Mchttasarım yorum toplama sistemi kurar.",
       ["Yorum bağlantısı/QR kodu hazırla.", "Personele yorum isteme rutinini anlat.", "Aylık yorum hedefi koy."],
       "Profilinize uzun süredir yeni yorum gelmemiş görünüyor. Düzenli yorum, profilin canlı ve güvenilir görünmesini sağlar.",
       "Google İşletme Profili optimizasyonu",
       ["Müşterilerden yorum istemeyi bırakmış olabilir misiniz?"],
       ["Yeni yorumlar geliyor mu?"]),

    # =============================================================== SOSYAL MEDYA
    _g("sosyal_yok", SOSYAL, "Sosyal medya hesabı bulunamadı", ["Sosyal Medya Yönetimi", "Grafik Tasarım"], ["social.social_presence", "web.social_links"],
       "Resmî web sitesinde ve kayıtlarda doğrulanabilir bir sosyal medya hesabı bulunamadı. Hesabın hiç olmadığı anlamına gelmez; arama motorları bu ortamda erişilemediği için yalnızca site ve kayıtlar tarandı.",
       "Sosyal medya, güven ve tekrar müşteri oluşturmanın önemli yollarından biridir; hesap yoksa ya da bağlantısız ise bu fırsat kaçabilir.",
       "Mchttasarım hesapları kurar/düzenler, içerik takvimi ve görselleri hazırlar, düzenli paylaşım yapar.",
       ["Görüşmede işletmenin sosyal medya hesabı olup olmadığını sor.", "Varsa hesap adresini not al; yoksa hangi platformun uygun olduğuna karar ver.", "Logo, fotoğraf ve marka renklerini topla.", "Aylık içerik planını hazırla.", "Hesap ve site bağlantılarını birbirine ekle."],
       "İşletmenizin sosyal medya hesaplarını sitenizde/kayıtlarda göremedik. Düzenli ve profesyonel bir hesap, müşterilerin sizi tanımasına ve tekrar gelmesine yardımcı olabilir.",
       "Sosyal medya yönetimi",
       ["Sosyal medya hesabınız var mı?", "Müşterileriniz sizi sosyal medyadan buluyor mu?", "İçerikleri kim hazırlıyor?"],
       ["Hesap profilleri eksiksiz mi?", "Site ve Google profili hesaba bağlı mı?", "İlk aylık içerik takvimi yayında mı?"]),

    _g("sosyal_aktif_degil", SOSYAL, "Sosyal medya hesabı aktif değil", ["Sosyal Medya Yönetimi"], [],
       "Hesap var ama uzun süredir paylaşım yapılmıyor olabilir. (Bu sistem paylaşım sıklığını otomatik ölçemez; görüşmede hesap birlikte incelenmelidir.)",
       "Sessiz bir hesap işletmenin kapalı ya da ilgisiz olduğu izlenimini verebilir.",
       "Mchttasarım hesabı yeniden canlandırır: içerik takvimi, görsel üretimi ve düzenli paylaşım.",
       ["Hesabı birlikte aç ve son paylaşım tarihine bak.", "Neden durduğunu sor (zaman, içerik fikri, kişi).", "Hedef ve içerik türlerini belirle.", "Aylık takvim hazırla.", "İlk hafta içerikleri yayınla."],
       "Hesabınızın son zamanlarda sessiz kaldığını görüyoruz. Düzenli içerikle hesabınızı canlandırıp müşterilerle bağı güçlendirebiliriz.",
       "Sosyal medya yönetimi",
       ["Hesabı en son ne zaman güncellediniz?", "İçerik üretmekte en çok neye zorlanıyorsunuz?"],
       ["Haftalık paylaşım düzeni oturdu mu?", "Etkileşim (beğeni/mesaj) artıyor mu?"]),

    _g("sosyal_duzensiz", SOSYAL, "İçerik düzensiz", ["Sosyal Medya Yönetimi", "Grafik Tasarım"], [],
       "Paylaşımlar düzensiz veya farklı görsel stillerde olabilir. (Görüşmede hesap birlikte incelenmelidir.)",
       "Düzensiz içerik takipçinin ilgisini kaybettirebilir ve marka algısını zayıflatabilir.",
       "Mchttasarım tutarlı bir içerik takvimi ve görsel şablonlar hazırlar.",
       ["Hesabı birlikte incele.", "Marka renk/yazı tipi kurallarını belirle.", "Şablonları tasarla.", "Aylık takvimi çıkar.", "Yayınları düzenli takip et."],
       "Paylaşımlarınızın düzenli ve aynı görsel dille olması, hesabınızı daha profesyonel gösterebilir.",
       "Sosyal medya yönetimi + grafik tasarım",
       ["Haftada kaç paylaşım yapmak istersiniz?", "Marka renkleriniz/logonuz hazır mı?"],
       ["Paylaşımlar takvime uygun mu?", "Görseller tutarlı mı?"]),

    _g("sosyal_profil", SOSYAL, "Profil eksikleri (biyografi, logo, bağlantı)", ["Sosyal Medya Yönetimi"], [],
       "Hesap profilinde logo, biyografi, iletişim butonu veya web sitesi bağlantısı eksik olabilir. (Görüşmede birlikte kontrol edilmelidir.)",
       "Eksik profil, hesaba giren kişinin işletmeyi tanımasını ve size ulaşmasını zorlaştırabilir.",
       "Mchttasarım profili logo, biyografi, iletişim ve bağlantılarla eksiksiz düzenler.",
       ["Profili birlikte aç ve eksikleri listele.", "Logo/biyografi metnini hazırla.", "İletişim butonlarını ve site bağlantısını ekle.", "Öne çıkan hikâyeleri düzenle."],
       "Hesabınızın profil bölümünde küçük eksikler var; tamamlanınca hesabı ziyaret eden kişi size daha kolay ulaşabilir.",
       "Sosyal medya yönetimi",
       ["Profildeki bilgiler güncel mi?", "Hesabınızdan sitenize yönlendirme var mı?"],
       ["Logo, biyografi ve bağlantılar tamam mı?"]),

    _g("sosyal_iletisim", SOSYAL, "Sosyal medyada iletişim eksikleri", ["Sosyal Medya Yönetimi"], [],
       "Hesapta iletişim bilgisi (telefon, WhatsApp, konum) eksik veya mesajlara geç yanıt veriliyor olabilir. (Görüşmede birlikte kontrol edilmelidir.)",
       "Mesajlara ulaşılamamak potansiyel müşteriyi kaybettirebilir.",
       "Mchttasarım iletişim butonlarını ekler, hazır yanıt şablonları ve mesaj takip süreci kurar.",
       ["Hesabın mesaj ve iletişim ayarlarını birlikte kontrol et.", "Hazır yanıtlar (mesai dışı, fiyat, adres) yaz.", "Mesajları kimin ve ne sürede yanıtlayacağını belirle."],
       "Sosyal medyada size yazanlara hızlı ve düzenli yanıt vermek satışa dönüşen görüşmeleri artırabilir.",
       "Sosyal medya yönetimi",
       ["Sosyal medya mesajlarına kim bakıyor?", "Mesajlardan satış oluyor mu?"],
       ["Hazır yanıtlar tanımlı mı?", "Mesaj yanıt süresi kısaldı mı?"]),

    # =============================================================== REKLAM
    _g("reklam_google_ads", REKLAM, "Google Ads fırsatı", ["Google Ads"], [],
       "Bu sektörde yerel arama talebi yüksek olabilir; işletmenin Google Ads kullanıp kullanmadığı bu sistem tarafından DOĞRULANAMADI (sektöre dayalı bir olasılıktır, tespit değildir).",
       "Google'da reklam, organik sıralama yükselene kadar ('{kelime} {sehir}' gibi) aramalarda hızlıca görünmeyi sağlayabilir.",
       "Mchttasarım anahtar kelime araştırması yapar, reklam hesabını kurar, reklam metinlerini yazar ve raporlar.",
       ["Görüşmede işletmenin reklam verip vermediğini sor.", "Aylık reklam bütçesi aralığını öğren.", "Hedef hizmetleri ve bölgeyi belirle.", "Anahtar kelime ve reklam metni planı hazırla.", "Kampanyayı kur, dönüşüm takibini ekle.", "Aylık rapor ver."],
       "{sehir} bölgesinde {kelime} arayan kişilere Google'da reklamla görünmeniz mümkün. Bütçenizi kontrol ederek başlayıp sonuçlara göre büyütebiliriz.",
       "Google Ads yönetimi",
       ["Şu anda Google'da reklam veriyor musunuz?", "Aylık ayırabileceğiniz bütçe nedir?", "Hangi hizmetten daha çok müşteri istiyorsunuz?"],
       ["Reklamlar yayında mı?", "Telefon/form dönüşümleri takip ediliyor mu?", "Aylık rapor paylaşıldı mı?"]),

    _g("reklam_yerel", REKLAM, "Yerel arama fırsatı", ["Yerel SEO", "Google Ads"], [],
       "Bölgedeki müşteriler '{kelime} {sehir}' gibi aramalar yapar; işletmenin bu aramalardaki görünürlüğü yalnızca Google'da elle test edilerek doğrulanabilir.",
       "Yerel aramalarda görünen işletmeler telefon ve ziyaret talebinin önemli bir kısmını alabilir.",
       "Mchttasarım Google İşletme Profili, yerel SEO ve gerekirse yerel reklamı birlikte yönetir.",
       ["Görüşme sırasında Google'da '{kelime} {sehir}' araması yap ve işletmenin nerede çıktığını gösterip sor.", "Rakiplerin görünümünü karşılaştır.", "Profil + site + reklam planını öner."],
       "Birlikte Google'da '{kelime} {sehir}' araması yapıp sizin ve rakiplerin nerede çıktığına bakalım; görünürlüğünüzü artırmak için neler yapılabileceğini konuşalım.",
       "Yerel SEO + Google İşletme Profili (+ isteğe bağlı Google Ads)",
       ["Yeni müşterilerinizin çoğu sizi nasıl buluyor?", "Google'da aradığınızda kendinizi görebiliyor musunuz?"],
       ["Yerel aramada sıralama takibe alındı mı?", "Profil aramalarından gelen telefon sayısı izleniyor mu?"]),

    _g("reklam_marka", REKLAM, "Marka görünürlüğü", ["Grafik Tasarım", "Kurumsal Kimlik", "Sosyal Medya Reklamları"], [],
       "İşletmenin markasının bölgede ne kadar tanındığı bu sistemle ölçülemez; görünürlük artırma ihtiyacı görüşmede sorularak anlaşılmalıdır.",
       "Marka tanınırlığı, insanların adınızı aramasını ve sizi tercih etmesini destekler.",
       "Mchttasarım kurumsal kimlik, sosyal medya reklamları ve dış mekân görünürlüğünü birlikte planlar.",
       ["İşletmenin hedef kitlesini ve bölgesini öğren.", "Mevcut logo/kimlik durumunu incele.", "Görünürlük kanallarını (sosyal medya, tabela, basılı) seç.", "Bütçeye göre plan sun."],
       "Bölgenizde markanızın daha çok kişi tarafından tanınması için görsel kimlik ve reklam çalışmalarını birlikte planlayabiliriz.",
       "Kurumsal kimlik + sosyal medya reklamları",
       ["Hedef müşteriniz kim?", "Markanızın tanınması için şu ana kadar ne yaptınız?"],
       ["Marka görselleri her kanalda tutarlı mı?", "Reklam erişimi raporlanıyor mu?"]),

    _g("reklam_donusum", REKLAM, "Dönüşüm takibi eksikleri", ["Web Tasarım", "Google Ads"], [],
       "Sitedeki aramaların/form gönderimlerinin ölçülüp ölçülmediği bu sistemle doğrulanamaz; görüşmede sorulmalıdır.",
       "Ölçüm yoksa hangi çalışmanın müşteri getirdiği anlaşılamaz ve bütçe verimsiz kullanılabilir.",
       "Mchttasarım telefon/WhatsApp/form dönüşümlerini takip edecek ölçüm altyapısını kurar.",
       ["İşletmeye sitedeki aramaları/formları takip edip etmediğini sor.", "Google Analytics/Ads hesabı erişimini iste.", "Telefon, WhatsApp ve form tıklamalarını ölçüme ekle.", "Aylık raporlama düzenini kur."],
       "Sitenizden ve reklamlardan kaç arama/mesaj geldiğini ölçebilirsek, hangi çalışmanın işe yaradığını net görebilirsiniz.",
       "Web sitesi + reklam ölçümleme (dönüşüm takibi)",
       ["Sitenizden gelen aramaları sayıyor musunuz?", "Reklam verdiyseniz sonuçları nasıl ölçüyordunuz?"],
       ["Telefon/WhatsApp/form dönüşümleri panelde görünüyor mu?"]),

    # =============================================================== MATBAA / PROMOSYON
    _g("matbaa_kartvizit", MATBAA, "Kartvizit", ["Matbaa", "Grafik Tasarım"], [],
       "İşletmenin güncel, profesyonel kartviziti olup olmadığı bu sistemle doğrulanamaz (sektöre dayalı olası ihtiyaç).",
       "Kartvizit, yüz yüze görüşmelerde ilk izlenimin ve iletişimin kalıcı bir parçasıdır.",
       "Mchttasarım kurumsal kimliğe uygun kartvizit tasarlar ve basar.",
       ["İşletmenin mevcut kartvizitini iste.", "Logo ve iletişim bilgilerini teyit et.", "Tasarım seçenekleri sun.", "Baskı türü ve adet için teklif ver.", "Onaydan sonra baskıya al ve teslim et."],
       "Kartvizitiniz işletmenizin ilk yüz yüze temsilcisi. Logonuza uygun, güncel bilgilerle yeni bir tasarım hazırlayabiliriz.",
       "Kartvizit tasarımı ve baskısı", ["Kartvizitleriniz güncel mi, bitmek üzere mi?", "Kaç kişi kartvizit kullanıyor?"], ["Bilgiler doğru mu?", "Renk ve baskı kalitesi onaylandı mı?"]),
    _g("matbaa_brosur", MATBAA, "Broşür / katalog", ["Matbaa", "Grafik Tasarım"], [],
       "İşletmenin hizmetlerini anlatan basılı bir broşür/kataloğu olup olmadığı doğrulanamaz (olası ihtiyaç).",
       "Basılı broşür, mekânda veya etkinliklerde hizmetleri kalıcı olarak tanıtır.",
       "Mchttasarım içerik toplama, tasarım ve baskıyı birlikte yürütür.",
       ["Anlatılacak hizmet ve fiyat bilgisini topla.", "Görselleri iste.", "Tasarım taslağını sun.", "Sayfa/adet/kağıt türü için teklif ver.", "Baskı öncesi kontrol ettir."],
       "Hizmetlerinizi mekânınızda ve etkinliklerde kalıcı biçimde tanıtacak bir broşür hazırlayabiliriz.",
       "Broşür/katalog tasarım ve baskı", ["Hizmetlerinizi anlatan basılı bir materyaliniz var mı?", "Hangi hizmetleri öne çıkarmak istersiniz?"], ["Baskı örneği onaylandı mı?", "Bilgiler güncel mi?"]),
    _g("matbaa_menu", MATBAA, "Menü", ["Matbaa", "Grafik Tasarım"], [],
       "Yeme-içme işletmesinde basılı menünün güncel/profesyonel olup olmadığı doğrulanamaz (olası ihtiyaç).",
       "Menü, müşterinin sipariş kararını doğrudan etkileyen materyaldir.",
       "Mchttasarım menü tasarımı, fotoğraf ve baskıyı (masa üstü, QR menü dahil) hazırlar.",
       ["Mevcut menüyü ve fiyatları al.", "Ürün fotoğraflarını değerlendir.", "Tasarım seçeneklerini sun.", "Baskı türünü seç (kâğıt, ahşap, plastik).", "Fiyat değişiminde güncelleme sürecini belirle."],
       "Menünüz sipariş kararını etkileyen önemli bir materyal. Marka görünümünüze uygun, okunaklı bir menü tasarlayabiliriz.",
       "Menü tasarımı ve baskısı", ["Menünüzü en son ne zaman yenilediniz?", "QR menü düşünür müsünüz?"], ["Fiyatlar ve içerik doğru mu?", "Baskı kalitesi onaylandı mı?"]),
    _g("matbaa_tabela", MATBAA, "Tabela", ["Tabela"], [],
       "İşletmenin tabelasının durumu bu sistemle doğrulanamaz (fiziksel mekânı olan sektörler için olası ihtiyaç); yerinde görülerek değerlendirilmelidir.",
       "Yoldan geçen müşteri işletmeyi tabelasından tanır; okunaklı ve güncel tabela fiziksel görünürlüğün temelidir.",
       "Mchttasarım tabela tasarımı, üretimi ve montajını yapar.",
       ["Mekânı ve mevcut tabelayı fotoğrafla.", "Ölçüleri al.", "Tasarım ve malzeme seçeneklerini sun.", "İzin/belediye gereksinimlerini kontrol et.", "Üret ve monte et."],
       "Mekânınızın dışarıdan görünürlüğü için tabelanızı birlikte değerlendirelim; gerekiyorsa yenileyebiliriz.",
       "Tabela tasarım, üretim ve montaj", ["Tabelanızdan memnun musunuz, gece görünüyor mu?", "Yenileme planınız var mı?"], ["Montaj güvenli ve düzgün mü?", "Işıklandırma çalışıyor mu?"]),
    _g("matbaa_branda", MATBAA, "Branda / afiş", ["Branda Baskı"], [],
       "Kampanya/duyuru için branda veya afiş ihtiyacı doğrulanamaz (olası ihtiyaç).",
       "Branda/afiş, kampanya ve duyuruları dışarıdan görünür kılar.",
       "Mchttasarım tasarım, baskı ve montajı yapar.",
       ["Kampanya/duyuru içeriğini öğren.", "Ölçüyü al.", "Tasarımı hazırla.", "Baskı ve montaj tarihini planla."],
       "Kampanyalarınızı dışarıdan görünür yapmak için branda/afiş hazırlayabiliriz.",
       "Branda/afiş baskı ve montaj", ["Yakında bir kampanya/açılış var mı?", "Hangi ölçüde alan uygun?"], ["Montaj sağlam mı?", "Baskı renkleri doğru mu?"]),
    _g("matbaa_promosyon", MATBAA, "Promosyon ürünleri", ["Promosyon Ürünleri"], [],
       "Logolu promosyon ürünü ihtiyacı doğrulanamaz (olası ihtiyaç).",
       "Logolu ürünler müşteriyi hatırlatır ve sadakati destekleyebilir.",
       "Mchttasarım logolu ürün seçimi, tasarım ve üretimi yapar.",
       ["Bütçe ve adedi öğren.", "Hedef müşteriye uygun ürün seç.", "Logo/tasarımı uygula.", "Numune onayı al.", "Üret ve teslim et."],
       "Müşterilerinize logolu küçük hediyeler vermek markanızı akılda tutmalarına yardımcı olabilir.",
       "Logolu promosyon ürünleri", ["Müşterilerinize hediye verir misiniz?", "Bütçe aralığınız nedir?"], ["Numune onaylandı mı?", "Teslimat adedi doğru mu?"]),
    _g("matbaa_davetiye", MATBAA, "Davetiye", ["Davetiye", "Grafik Tasarım"], [],
       "Etkinlik/düğün gibi organizasyon yapan işletmeler için davetiye ihtiyacı doğrulanamaz (olası ihtiyaç).",
       "Davetiye, etkinliğin ilk izlenimidir.",
       "Mchttasarım davetiye tasarımı ve baskısı yapar.",
       ["Etkinlik türünü ve tarihini öğren.", "Metin ve adedi belirle.", "Tasarım seçeneklerini sun.", "Örnek onayı sonrası baskı yap."],
       "Etkinlikleriniz için özel tasarım davetiyeler hazırlayabiliriz.",
       "Davetiye tasarım ve baskı", ["Yaklaşan bir etkinlik var mı?", "Kaç davetiye gerekli?"], ["Bilgiler doğru mu?", "Baskı kalitesi onaylandı mı?"]),
    _g("matbaa_kurumsal", MATBAA, "Kurumsal materyaller", ["Kurumsal Kimlik", "Matbaa"], [],
       "Antetli kâğıt, zarf, dosya gibi kurumsal basılı materyallerin durumu doğrulanamaz (olası ihtiyaç).",
       "Tutarlı kurumsal materyaller profesyonellik algısını destekler.",
       "Mchttasarım kurumsal kimlik setini tasarlar ve basar.",
       ["Mevcut materyalleri ve logoyu incele.", "Kurumsal set kapsamını belirle.", "Tasarım ve baskı için teklif ver."],
       "Kurumsal materyalleriniz tek bir görsel dille hazırlanırsa işletmeniz daha profesyonel görünebilir.",
       "Kurumsal kimlik ve basılı set", ["Antetli kâğıt/zarf gibi materyal kullanıyor musunuz?", "Logonuz güncel mi?"], ["Tüm materyaller aynı kimlikte mi?"]),
    _g("arac_giydirme", MATBAA, "Araç giydirme", ["Araç Giydirme"], [],
       "Filo/servis aracı kullanan sektörler için araç giydirme ihtiyacı doğrulanamaz (olası ihtiyaç; işletmenin aracı olup olmadığı bilinmiyor).",
       "Araçlar hareketli reklam alanıdır ve bölgede görünürlük sağlayabilir.",
       "Mchttasarım araç ölçüsüne göre tasarım, baskı ve uygulamayı yapar.",
       ["İşletmenin araç sayısı ve türünü öğren.", "Araç ölçülerini ve fotoğraflarını al.", "Tasarım öner.", "Uygulama tarihini planla."],
       "Araçlarınız gün boyu şehirde dolaşıyorsa, üzerine yapılacak bir giydirme markanızı ücretsiz bir reklam alanına çevirebilir.",
       "Araç giydirme", ["Kaç aracınız var?", "Araçlar hangi bölgelerde dolaşıyor?"], ["Uygulama kabarcıksız ve düzgün mü?", "Tüm iletişim bilgileri okunaklı mı?"]),
    _g("foto_video", MATBAA, "Fotoğraf / video içerik", ["Fotoğraf ve Video İçerik"], [],
       "İşletmenin güncel profesyonel fotoğraf/videosu olup olmadığı görüşmede değerlendirilmelidir (olası ihtiyaç).",
       "Kaliteli görsel; profil, site ve sosyal medyada güveni ve tıklamayı artırabilir.",
       "Mchttasarım mekân/ürün/ekip fotoğrafı ve tanıtım videosu çekimi yapar.",
       ["Kullanılacak yerleri belirle (profil, site, sosyal medya).", "Çekim planı ve tarihi belirle.", "Çekim yap ve düzenle.", "Görselleri ilgili kanallara yükle."],
       "Profesyonel bir fotoğraf/video çekimi, profilinizi ve sitenizi daha güven verici yapabilir.",
       "Fotoğraf/video çekimi", ["Güncel fotoğraflarınız var mı?", "Tanıtım videosu ister misiniz?"], ["Görseller yayına alındı mı?"]),
    _g("kurumsal_kimlik", MATBAA, "Kurumsal kimlik / logo", ["Kurumsal Kimlik", "Grafik Tasarım"], [],
       "Logo ve kurumsal kimliğin durumu görüşmede değerlendirilmelidir (olası ihtiyaç).",
       "Tutarlı bir marka kimliği hem dijitalde hem fiziksel mekânda güven ve tanınırlık sağlayabilir.",
       "Mchttasarım logo, renk/yazı sistemi ve marka kılavuzu hazırlar; tüm materyallere uygular.",
       ["Mevcut logo ve kullanımını incele.", "Marka değerlerini ve hedef kitleyi öğren.", "Logo ve kimlik seçeneklerini sun.", "Kılavuz ve materyalleri hazırla."],
       "Markanızı her yerde aynı ve profesyonel göstermek için kurumsal kimlik çalışması yapabiliriz.",
       "Kurumsal kimlik tasarımı", ["Logonuzdan memnun musunuz?", "Tüm materyallerde aynı logo/renkler mi kullanılıyor?"], ["Marka kılavuzu teslim edildi mi?"]),
]

GUIDES: dict[str, Guide] = {g.id: g for g in _GUIDES}

# Analizdeki kontrol → rehber eşlemesi ("<alan>.<anahtar>"; alan: web | gbp | social)
CHECK_TO_GUIDE: dict[str, str] = {}
for _guide in _GUIDES:
    for _key in _guide.check_keys:
        CHECK_TO_GUIDE[_key] = _guide.id

# Rehberi gerektirmeyen (satış sorunu olmayan) kontroller
NO_GUIDE_CHECKS = {"gbp.business_status"}

# Hizmet → ilgili rehber (fırsat kartlarındaki "Nasıl çözülür?" için, kanıtlı sorun bulunmayan olası ihtiyaçlarda)
SERVICE_TO_GUIDE = {
    "Google Ads": "reklam_google_ads", "Yerel SEO": "reklam_yerel", "Sosyal Medya Reklamları": "reklam_marka", "Matbaa": "matbaa_kartvizit",
    "Tabela": "matbaa_tabela", "Branda Baskı": "matbaa_branda", "Promosyon Ürünleri": "matbaa_promosyon", "Davetiye": "matbaa_davetiye",
    "Araç Giydirme": "arac_giydirme", "Fotoğraf ve Video İçerik": "foto_video", "Kurumsal Kimlik": "kurumsal_kimlik", "Grafik Tasarım": "kurumsal_kimlik",
    "Sosyal Medya Yönetimi": "sosyal_yok", "Kurumsal Web Sitesi": "web_yok", "E-Ticaret": "web_eticaret",
}


def guide_for_check(area: str, key: str) -> Guide | None:
    area = "web" if area == "website" else area  # analizde alan adı "website"; rehber eşlemesinde "web"
    guide_id = CHECK_TO_GUIDE.get(f"{area}.{key}")
    return GUIDES.get(guide_id) if guide_id else None


def render_guide(guide: Guide, *, business: str | None = None, place: str | None = None, sector: str | None = None, phrase: str | None = None) -> dict:
    """Yer tutucuları doldurur. İşletme bilgisi yoksa genel ifadeler kullanılır (uydurma isim/şehir yazılmaz)."""
    values = {
        "isletme": business or "işletmeniz",
        "sehir": place or "bölgenizde",
        "sektor": sector or "sektörünüzde",
        "kelime": phrase or (sector.lower() if sector else "hizmet"),
    }

    def fill(text: str) -> str:
        for key, value in values.items():
            text = text.replace("{" + key + "}", value)
        return text

    return {
        "id": guide.id, "category": guide.category, "title": guide.title, "services": list(guide.services), "check_keys": list(guide.check_keys),
        "sections": {
            "what": fill(guide.what), "why": fill(guide.why), "solution": fill(guide.solution), "steps": [fill(s) for s in guide.steps],
            "pitch": fill(guide.pitch), "offer": fill(guide.offer), "questions": [fill(q) for q in guide.questions], "verify": [fill(v) for v in guide.verify],
        },
    }
