"""Sektör listesi (tamamı Türkçe) — gruplu, Türkçe arama ifadeleriyle.

Her kayıt: (sektör adı, grup, arama_ifadeleri)

- arama_ifadeleri: Google Haritalar'da "<ifade> <ilçe> <il>" biçiminde aranır. İLK ifade birincil arama terimidir
  (örn. "işitme cihazı"); sonuç yetersizse sektör adı ikinci sorgu olarak denenir.
- Eşleştirmede ve site/başlık kontrollerinde de bu ifadeler kullanılır (işletme adı/başlık sektörü anlatıyor mu?).

Listeye yeni sektör eklemek için satır ekleyip `python -m packages.db.seed` çalıştırmak yeterlidir.
"""

SECTORS: list[tuple[str, str, list[str]]] = [
    # ---------------------------------------------------------------- Sağlık ve Tıp
    ("Diş Kliniği", "Sağlık ve Tıp", ["diş kliniği", "diş hekimi", "ağız ve diş", "diş polikliniği"]),
    ("Özel Klinik / Poliklinik", "Sağlık ve Tıp", ["poliklinik", "tıp merkezi", "özel klinik"]),
    ("Doktor Muayenehanesi", "Sağlık ve Tıp", ["muayenehane"]),
    ("Özel Hastane", "Sağlık ve Tıp", ["hastane"]),
    ("Eczane", "Sağlık ve Tıp", ["eczane"]),
    ("Optik / Gözlükçü", "Sağlık ve Tıp", ["optik", "gözlükçü"]),
    ("İşitme Cihazı Merkezi", "Sağlık ve Tıp", ["işitme cihazı", "işitme merkezi", "işitme", "odyoloji", "odyolog"]),
    ("Fizik Tedavi ve Rehabilitasyon", "Sağlık ve Tıp", ["fizik tedavi", "fizyoterapi", "rehabilitasyon"]),
    ("Psikolog / Psikolojik Danışmanlık", "Sağlık ve Tıp", ["psikolog", "psikolojik danışmanlık", "terapi merkezi"]),
    ("Diyetisyen", "Sağlık ve Tıp", ["diyetisyen", "beslenme danışmanı"]),
    ("Tıbbi Laboratuvar", "Sağlık ve Tıp", ["laboratuvar", "tıbbi tahlil"]),
    ("Medikal Malzeme / Ortopedi", "Sağlık ve Tıp", ["medikal", "ortopedi", "tıbbi malzeme"]),
    ("Veteriner", "Sağlık ve Tıp", ["veteriner", "veteriner kliniği"]),
    ("Estetik ve Lazer Merkezi", "Sağlık ve Tıp", ["estetik", "lazer epilasyon", "cilt bakım merkezi"]),
    # ---------------------------------------------------------------- Güzellik ve Kişisel Bakım
    ("Güzellik Salonu", "Güzellik ve Kişisel Bakım", ["güzellik salonu", "güzellik merkezi"]),
    ("Kuaför / Berber", "Güzellik ve Kişisel Bakım", ["kuaför", "berber"]),
    ("Spa ve Masaj Salonu", "Güzellik ve Kişisel Bakım", ["spa", "masaj", "hamam"]),
    ("Dövme Stüdyosu", "Güzellik ve Kişisel Bakım", ["dövme", "piercing"]),
    ("Kozmetik / Parfümeri", "Güzellik ve Kişisel Bakım", ["kozmetik", "parfümeri"]),
    # ---------------------------------------------------------------- Yeme-İçme
    ("Restoran", "Yeme-İçme", ["restoran", "lokanta", "restaurant"]),
    ("Kafe", "Yeme-İçme", ["kafe", "cafe", "kahve"]),
    ("Hızlı Yemek / Büfe", "Yeme-İçme", ["büfe", "döner", "hamburger"]),
    ("Pastane ve Tatlıcı", "Yeme-İçme", ["pastane", "tatlıcı", "baklava"]),
    ("Fırın", "Yeme-İçme", ["fırın", "unlu mamül"]),
    ("Kasap", "Yeme-İçme", ["kasap", "et ürünleri"]),
    ("Manav", "Yeme-İçme", ["manav"]),
    ("Şarküteri", "Yeme-İçme", ["şarküteri"]),
    ("Kuruyemiş ve Şekerleme", "Yeme-İçme", ["kuruyemiş", "şekerleme"]),
    ("Dondurmacı", "Yeme-İçme", ["dondurma"]),
    ("Bar / Meyhane", "Yeme-İçme", ["meyhane", "bar"]),
    ("Catering / Toplu Yemek", "Yeme-İçme", ["catering", "toplu yemek", "yemek hizmetleri"]),
    # ---------------------------------------------------------------- Konaklama ve Turizm
    ("Otel", "Konaklama ve Turizm", ["otel", "hotel"]),
    ("Pansiyon ve Apart", "Konaklama ve Turizm", ["pansiyon", "apart otel", "apart"]),
    ("Bungalov ve Tatil Köyü", "Konaklama ve Turizm", ["bungalov", "tatil köyü"]),
    ("Kamp ve Karavan Alanı", "Konaklama ve Turizm", ["kamp alanı", "karavan"]),
    ("Seyahat Acentesi", "Konaklama ve Turizm", ["seyahat acentesi", "turizm", "tur"]),
    # ---------------------------------------------------------------- Otomotiv
    ("Oto Galeri", "Otomotiv", ["oto galeri", "ikinci el araç", "otomotiv"]),
    ("Oto Servis ve Tamir", "Otomotiv", ["oto servis", "oto tamir", "yetkili servis"]),
    ("Oto Yıkama", "Otomotiv", ["oto yıkama"]),
    ("Lastikçi", "Otomotiv", ["lastik"]),
    ("Oto Yedek Parça", "Otomotiv", ["yedek parça", "oto yedek"]),
    ("Motosiklet Bayii", "Otomotiv", ["motosiklet"]),
    ("Oto Kiralama", "Otomotiv", ["rent a car", "araç kiralama", "oto kiralama"]),
    ("Akaryakıt İstasyonu", "Otomotiv", ["akaryakıt", "petrol"]),
    ("Oto Kaporta ve Boya", "Otomotiv", ["oto kaporta", "oto boya", "kaporta boya"]),
    # ---------------------------------------------------------------- Emlak, İnşaat ve Yapı
    ("Emlak Ofisi", "Emlak, İnşaat ve Yapı", ["emlak", "gayrimenkul"]),
    ("İnşaat Firması", "Emlak, İnşaat ve Yapı", ["inşaat", "müteahhit"]),
    ("Mimarlık Ofisi", "Emlak, İnşaat ve Yapı", ["mimarlık", "mimar"]),
    ("Mühendislik ve Müşavirlik", "Emlak, İnşaat ve Yapı", ["mühendislik", "müşavirlik"]),
    ("Yapı Malzemeleri", "Emlak, İnşaat ve Yapı", ["yapı market", "yapı malzemeleri", "inşaat malzemeleri"]),
    ("Hırdavat ve Nalbur", "Emlak, İnşaat ve Yapı", ["hırdavat", "nalbur"]),
    ("Boya ve Badana", "Emlak, İnşaat ve Yapı", ["boya"]),
    ("Seramik ve Fayans", "Emlak, İnşaat ve Yapı", ["seramik", "fayans"]),
    ("Elektrik Taahhüt", "Emlak, İnşaat ve Yapı", ["elektrik taahhüt", "elektrikçi"]),
    ("Tesisat ve Isıtma-Soğutma", "Emlak, İnşaat ve Yapı", ["tesisat", "kombi", "klima servisi"]),
    ("Marangoz ve Ahşap İşleri", "Emlak, İnşaat ve Yapı", ["marangoz", "ahşap"]),
    ("Çilingir", "Emlak, İnşaat ve Yapı", ["çilingir"]),
    ("Cam ve Doğrama", "Emlak, İnşaat ve Yapı", ["cam balkon", "pvc doğrama", "alüminyum doğrama"]),
    ("Peyzaj ve Fidanlık", "Emlak, İnşaat ve Yapı", ["peyzaj", "fidanlık"]),
    # ---------------------------------------------------------------- Ev, Mobilya ve Dekorasyon
    ("Mobilya", "Ev, Mobilya ve Dekorasyon", ["mobilya"]),
    ("Mutfak ve Banyo", "Ev, Mobilya ve Dekorasyon", ["mutfak dolabı", "banyo"]),
    ("Beyaz Eşya", "Ev, Mobilya ve Dekorasyon", ["beyaz eşya"]),
    ("Perde ve Ev Tekstili", "Ev, Mobilya ve Dekorasyon", ["perde", "ev tekstili"]),
    ("Halı ve Kilim", "Ev, Mobilya ve Dekorasyon", ["halı", "kilim"]),
    ("Yatak ve Baza", "Ev, Mobilya ve Dekorasyon", ["yatak", "baza"]),
    ("Aydınlatma / Avize", "Ev, Mobilya ve Dekorasyon", ["aydınlatma", "avize"]),
    ("Dekorasyon", "Ev, Mobilya ve Dekorasyon", ["dekorasyon"]),
    ("Züccaciye ve Ev Eşyası", "Ev, Mobilya ve Dekorasyon", ["züccaciye", "ev eşyası"]),
    # ---------------------------------------------------------------- Perakende ve Mağazacılık
    ("Market", "Perakende ve Mağazacılık", ["market", "süpermarket", "bakkal"]),
    ("Giyim Mağazası", "Perakende ve Mağazacılık", ["giyim", "butik", "tekstil"]),
    ("Bebek ve Çocuk Ürünleri", "Perakende ve Mağazacılık", ["bebek", "çocuk giyim"]),
    ("Ayakkabı Mağazası", "Perakende ve Mağazacılık", ["ayakkabı"]),
    ("Çanta ve Aksesuar", "Perakende ve Mağazacılık", ["çanta", "aksesuar"]),
    ("Kuyumcu", "Perakende ve Mağazacılık", ["kuyumcu", "mücevher", "altın"]),
    ("Saat Mağazası", "Perakende ve Mağazacılık", ["saat"]),
    ("Oyuncak", "Perakende ve Mağazacılık", ["oyuncak"]),
    ("Spor Malzemeleri", "Perakende ve Mağazacılık", ["spor malzemeleri", "spor mağazası"]),
    ("Kitabevi", "Perakende ve Mağazacılık", ["kitabevi", "kitap"]),
    ("Kırtasiye", "Perakende ve Mağazacılık", ["kırtasiye"]),
    ("Hediyelik Eşya", "Perakende ve Mağazacılık", ["hediyelik", "hediye"]),
    ("Çiçekçi", "Perakende ve Mağazacılık", ["çiçekçi", "çiçek"]),
    ("Elektronik", "Perakende ve Mağazacılık", ["elektronik"]),
    ("Telefon Mağazası", "Perakende ve Mağazacılık", ["cep telefonu", "gsm", "telefon"]),
    ("Bilgisayar ve Teknoloji", "Perakende ve Mağazacılık", ["bilgisayar", "teknoloji"]),
    ("Bisiklet", "Perakende ve Mağazacılık", ["bisiklet"]),
    ("Evcil Hayvan Mağazası", "Perakende ve Mağazacılık", ["pet shop", "petshop", "evcil hayvan"]),
    ("Tarım ve Ziraat Malzemeleri", "Perakende ve Mağazacılık", ["ziraat", "tohum", "gübre"]),
    ("Antika ve İkinci El", "Perakende ve Mağazacılık", ["antika", "ikinci el", "spot"]),
    # ---------------------------------------------------------------- Profesyonel Hizmetler
    ("Sigorta Acentesi", "Profesyonel Hizmetler", ["sigorta"]),
    ("Hukuk Bürosu", "Profesyonel Hizmetler", ["hukuk bürosu", "avukat"]),
    ("Muhasebe ve Mali Müşavirlik", "Profesyonel Hizmetler", ["muhasebe", "mali müşavir", "smmm"]),
    ("Noter", "Profesyonel Hizmetler", ["noter"]),
    ("Finans ve Kredi", "Profesyonel Hizmetler", ["finansman", "kredi", "faktoring"]),
    ("Danışmanlık", "Profesyonel Hizmetler", ["danışmanlık"]),
    ("İnsan Kaynakları ve İş Bulma", "Profesyonel Hizmetler", ["insan kaynakları", "iş bulma", "kariyer"]),
    ("Güvenlik ve Alarm Sistemleri", "Profesyonel Hizmetler", ["güvenlik sistemleri", "alarm sistemleri", "kamera sistemleri"]),
    ("Temizlik Şirketi", "Profesyonel Hizmetler", ["temizlik şirketi", "temizlik firması"]),
    ("Organizasyon ve Etkinlik", "Profesyonel Hizmetler", ["organizasyon", "etkinlik"]),
    ("Düğün ve Davet Salonu", "Profesyonel Hizmetler", ["düğün salonu", "davet salonu"]),
    ("Fotoğraf ve Video Stüdyosu", "Profesyonel Hizmetler", ["fotoğrafçı", "fotoğraf stüdyosu", "video prodüksiyon"]),
    # ---------------------------------------------------------------- Reklam, Yazılım ve Medya
    ("Reklam Ajansı", "Reklam, Yazılım ve Medya", ["reklam ajansı", "reklam"]),
    ("Web Tasarım ve Yazılım", "Reklam, Yazılım ve Medya", ["web tasarım", "yazılım", "bilişim"]),
    ("Matbaa ve Baskı", "Reklam, Yazılım ve Medya", ["matbaa", "baskı", "dijital baskı"]),
    ("Tabelacı / Reklam Uygulama", "Reklam, Yazılım ve Medya", ["tabela", "reklam uygulama", "folyo"]),
    ("Promosyon Ürünleri Tedarikçisi", "Reklam, Yazılım ve Medya", ["promosyon", "promosyon ürünleri"]),
    ("Gazete ve Yayıncılık", "Reklam, Yazılım ve Medya", ["gazete", "yayıncılık"]),
    # ---------------------------------------------------------------- Eğitim
    ("Özel Okul", "Eğitim", ["özel okul", "koleji"]),
    ("Anaokulu ve Kreş", "Eğitim", ["anaokulu", "kreş"]),
    ("Dershane ve Etüt Merkezi", "Eğitim", ["dershane", "etüt merkezi"]),
    ("Yabancı Dil Okulu", "Eğitim", ["dil okulu", "yabancı dil"]),
    ("Sürücü Kursu", "Eğitim", ["sürücü kursu", "direksiyon"]),
    ("Müzik ve Sanat Kursu", "Eğitim", ["müzik kursu", "sanat merkezi", "bale"]),
    ("Mesleki ve Bilgisayar Kursu", "Eğitim", ["meslek kursu", "bilgisayar kursu", "eğitim merkezi"]),
    # ---------------------------------------------------------------- Spor, Etkinlik ve Eğlence
    ("Spor Salonu", "Spor, Etkinlik ve Eğlence", ["spor salonu", "fitness", "gym"]),
    ("Pilates ve Yoga Stüdyosu", "Spor, Etkinlik ve Eğlence", ["pilates", "yoga"]),
    ("Spor Kompleksi ve Yüzme", "Spor, Etkinlik ve Eğlence", ["spor kompleksi", "yüzme"]),
    ("Halı Saha", "Spor, Etkinlik ve Eğlence", ["halı saha"]),
    ("Oyun Salonu ve Eğlence Merkezi", "Spor, Etkinlik ve Eğlence", ["oyun salonu", "bowling", "playstation"]),
    # ---------------------------------------------------------------- Ulaşım ve Lojistik
    ("Nakliyat", "Ulaşım ve Lojistik", ["nakliyat", "nakliye", "evden eve"]),
    ("Kargo ve Kurye", "Ulaşım ve Lojistik", ["kargo", "kurye"]),
    ("Taksi ve Transfer", "Ulaşım ve Lojistik", ["taksi", "transfer"]),
    ("Lojistik ve Depolama", "Ulaşım ve Lojistik", ["lojistik", "depolama"]),
    # ---------------------------------------------------------------- Sanayi, Toptan ve Tarım
    ("Kontrplak ve Ahşap Levha", "Sanayi, Toptan ve Tarım", ["kontrplak", "ahşap levha", "sunta", "mdf"]),
    ("Ambalaj ve Plastik", "Sanayi, Toptan ve Tarım", ["ambalaj", "plastik"]),
    ("Demir Çelik ve Metal", "Sanayi, Toptan ve Tarım", ["demir çelik", "metal", "çelik"]),
    ("Konfeksiyon ve Tekstil Üretimi", "Sanayi, Toptan ve Tarım", ["konfeksiyon", "tekstil üretim"]),
    ("Toptan Ticaret", "Sanayi, Toptan ve Tarım", ["toptan"]),
    ("Makine ve Endüstriyel Ekipman", "Sanayi, Toptan ve Tarım", ["makine", "endüstriyel ekipman"]),
    ("Enerji ve Güneş Paneli", "Sanayi, Toptan ve Tarım", ["güneş enerjisi", "solar", "enerji sistemleri"]),
    # ---------------------------------------------------------------- Kişisel Hizmetler ve Tamir
    ("Kuru Temizleme ve Çamaşırhane", "Kişisel Hizmetler ve Tamir", ["kuru temizleme", "çamaşırhane"]),
    ("Halı Yıkama", "Kişisel Hizmetler ve Tamir", ["halı yıkama"]),
    ("Terzi ve Tadilat", "Kişisel Hizmetler ve Tamir", ["terzi", "tadilat"]),
    ("Ayakkabı Tamiri", "Kişisel Hizmetler ve Tamir", ["ayakkabı tamiri", "kunduracı"]),
    ("Teknik Servis (Telefon/Bilgisayar)", "Kişisel Hizmetler ve Tamir", ["telefon tamiri", "bilgisayar tamiri", "teknik servis"]),
    ("Cenaze Hizmetleri", "Kişisel Hizmetler ve Tamir", ["cenaze"]),
]

# Eski (İngilizce/karışık/yinelenen) adlardan yeni Türkçe adlara — mevcut işletme kayıtları bozulmadan taşınır.
SECTOR_RENAMES: dict[str, str] = {
    "Fast Food": "Hızlı Yemek / Büfe",
    "Pet Shop": "Evcil Hayvan Mağazası",
    "Plywood / Kontrplak": "Kontrplak ve Ahşap Levha",
    "Kuaför": "Kuaför / Berber",
    "Pastane": "Pastane ve Tatlıcı",
    "Özel Klinik": "Özel Klinik / Poliklinik",
    "Emlak": "Emlak Ofisi",
    "İnşaat": "İnşaat Firması",
    "Mimarlık": "Mimarlık Ofisi",
    "Mühendislik": "Mühendislik ve Müşavirlik",
    "Mutfak": "Mutfak ve Banyo",
    "Oto Servis": "Oto Servis ve Tamir",
    "Sigorta": "Sigorta Acentesi",
    "Finans": "Finans ve Kredi",
    "Muhasebe": "Muhasebe ve Mali Müşavirlik",
    "Matbaa": "Matbaa ve Baskı",
    "Web Tasarım": "Web Tasarım ve Yazılım",
    "Fotoğrafçı": "Fotoğraf ve Video Stüdyosu",
    "Organizasyon": "Organizasyon ve Etkinlik",
    "Bungalov": "Bungalov ve Tatil Köyü",
    "Perde / Tekstil": "Perde ve Ev Tekstili",
    "Optik": "Optik / Gözlükçü",
    "Kargo": "Kargo ve Kurye",
    "Hırdavat": "Hırdavat ve Nalbur",
    "Düğün Salonu": "Düğün ve Davet Salonu",
    "Spor Salonu": "Spor Salonu"
}

# Artık seçim listesinde olmaması gereken eski kayıtlar (yerlerine yenileri var). Kullanımda ise silinmez, sadece pasife alınır.
OBSOLETE_SECTOR_NAMES: list[str] = [
    "Berber",
    "Yazılım",
    "Eğitim / Kurs",
    "Web Tasarım İhtiyacı Olabilecek Tüm İşletmeler",
    "Kuaför / Güzellik Salonu",
    "Otomotiv Servisi"
]
